# Generated by Django 4.2.16 on 2024-12-31 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('widget', models.CharField(choices=[('Sales Amount by Party', 'Sales Amount by Party'), ('Sales Amount by Agent', 'Sales Amount by Agent'), ('Sales Count by Agent', 'Sales Count by Agent'), ('Sales Count by Party', 'Sales Count by Party'), ('Purchase Count by Party', 'Purchase Count by Party'), ('Total Purchase Amount', 'Total Purchase Amount'), ('Total Sales Amount', 'Total Sales Amount'), ('Sales Count by Mode', 'Sales Count by Mode'), ('Purchase Count by Mode', 'Purchase Count by Mode')], max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('group_by', models.CharField(choices=[('Day', 'Day(s)'), ('Week', 'Week(s)'), ('Month', 'Month(s)'), ('Year', 'Year(s)')], default='Day', max_length=10)),
                ('count', models.PositiveSmallIntegerField(default=7)),
                ('display_type', models.CharField(choices=[('Table', 'Table'), ('Bar', 'Bar'), ('Line', 'Line'), ('Radar', 'Radar'), ('Pie', 'Pie'), ('Doughnut', 'Doughnut'), ('Polar Area', 'Polar Area'), ('Mixed', 'Mixed')], default='Table', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
