# Generated by Django 4.2.20 on 2025-05-06 11:30

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0010_alter_company_tax_identification_number'),
        ('product', '0006_remove_inventorysetting_mandate_category_and_more'),
        ('tax', '0003_alter_taxscheme_short_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ledger', '0005_alter_account_current_cr_alter_account_current_dr_and_more'),
        ('voucher', '0009_alter_landedcostrow_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('generated_datetime', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Generated', 'Generated'), ('Sent', 'Sent'), ('Converted', 'Converted')], default='Draft', max_length=15)),
                ('discount', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))])),
                ('discount_type', models.CharField(blank=True, choices=[('Amount', 'Amount'), ('Percent', 'Percent')], max_length=15, null=True)),
                ('trade_discount', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_export', models.BooleanField(default=False)),
                ('total_amount', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='company.company')),
                ('discount_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='voucher.salesdiscount')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='company.fiscalyear')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='ledger.party')),
                ('sales_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='voucher.salesagent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('company', 'number')},
            },
        ),
        migrations.CreateModel(
            name='QuotationRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))])),
                ('rate', models.DecimalField(decimal_places=6, max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))])),
                ('discount', models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))])),
                ('discount_type', models.CharField(blank=True, choices=[('Amount', 'Amount'), ('Percent', 'Percent')], max_length=15, null=True)),
                ('trade_discount', models.BooleanField(default=False)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))])),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))])),
                ('net_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))])),
                ('discount_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_rows', to='voucher.salesdiscount')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_rows', to='product.item')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='quotation.quotation')),
                ('tax_scheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotation_rows', to='tax.taxscheme')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_rows', to='product.unit')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
