# Generated by Django 4.2.20 on 2025-05-07 05:25

from django.db import migrations, models
import django.db.models.deletion


def create_quotation_setting_for_existing_companies(apps, schema_editor):
    Company = apps.get_model('company', 'Company')
    QuotationSetting = apps.get_model('quotation', 'QuotationSetting')

    companies = Company.objects.all()

    quotation_settings = [
        QuotationSetting(company=company) for company in companies
    ]

    QuotationSetting.objects.bulk_create(quotation_settings)

class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_alter_company_tax_identification_number'),
        ('quotation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_text', models.TextField(blank=True, null=True)),
                ('footer_text', models.TextField(blank=True, null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_setting', to='company.company')),
            ],
        ),
        migrations.RunPython(
            create_quotation_setting_for_existing_companies,
            migrations.RunPython.noop,
        ),
    ]
