# Generated by Django 4.2.20 on 2025-05-07 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_alter_company_tax_identification_number'),
        ('quotation', '0002_quotationsetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='fiscal_year',
        ),
        migrations.AlterField(
            model_name='quotationsetting',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_settings', to='company.company'),
        ),
    ]
