# Generated by Django 4.2.20 on 2025-05-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0003_remove_quotation_fiscal_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
