# Generated by Django 4.2.20 on 2025-05-08 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0004_quotation_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='is_export',
        ),
    ]
