# Generated by Django 4.2.20 on 2025-05-13 12:26

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0005_remove_quotation_is_export'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationrow',
            name='quantity',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))]),
        ),
    ]
