# Generated by Django 4.2.20 on 2025-06-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0006_alter_quotationrow_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='tax_type',
            field=models.CharField(choices=[('Tax Exclusive', 'Tax Exclusive'), ('Tax Inclusive', 'Tax Inclusive'), ('No Tax', 'No Tax')], default='Tax Exclusive', max_length=15),
        ),
    ]
