# Generated by Django 4.2.17 on 2025-03-11 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_alter_company_tax_identification_number'),
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='party',
            old_name='tax_registration_number',
            new_name='tax_identification_number',
        ),
        migrations.AlterUniqueTogether(
            name='party',
            unique_together={('company', 'tax_identification_number')},
        ),
    ]
