# Generated by Django 4.2.17 on 2025-03-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_rename_tax_registration_number_party_tax_identification_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='tax_identification_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
