# Generated by Django 4.2.17 on 2025-04-01 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_alter_party_tax_identification_number'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE OR REPLACE FUNCTION merge_jsonb_agg(jsonb, jsonb)
            RETURNS jsonb AS $$
                BEGIN
                    RETURN (SELECT jsonb_agg(DISTINCT value) FROM jsonb_array_elements(COALESCE($1, '[]') || COALESCE($2, '[]')) AS value);
                END;
            $$ LANGUAGE plpgsql;
            CREATE OR REPLACE AGGREGATE jsonb_concat(jsonb) ( SFUNC = merge_jsonb_agg, STYPE = jsonb, INITCOND = '[]' );
            """
        ),
    ]
