# Generated by Django 2.1.5 on 2019-03-03 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_auto_20190303_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='party', to='ledger.Account'),
        ),
    ]
