# Generated by Django 4.2.17 on 2025-04-11 07:37

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_auto_20250401_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='current_cr',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='account',
            name='current_dr',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='account',
            name='opening_cr',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='account',
            name='opening_dr',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='account',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='accountopeningbalance',
            name='opening_cr',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='accountopeningbalance',
            name='opening_dr',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='cr_amount',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='current_cr',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='current_dr',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='dr_amount',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
    ]
