# Generated by Django 4.2.20 on 2025-05-09 08:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ledger", "0005_alter_account_current_cr_alter_account_current_dr_and_more"),
    ]

    operations = []
