# Generated by Django 2.1.5 on 2019-03-04 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_auto_20190303_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='customer_account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_detail', to='ledger.Account'),
        ),
        migrations.AddField(
            model_name='party',
            name='supplier_account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_detail', to='ledger.Account'),
        ),
    ]
