# Generated by Django 2.1.5 on 2019-03-10 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_auto_20190304_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyRepresentative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.Party')),
            ],
        ),
    ]
