# Generated by Django 2.1.5 on 2019-03-10 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0007_partyrepresentative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partyrepresentative',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representative', to='ledger.Party'),
        ),
    ]
