# Generated by Django 2.1.5 on 2019-03-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0008_auto_20190310_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='partyrepresentative',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
