# Generated by Django 2.1.5 on 2019-07-25 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0009_partyrepresentative_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='account',
        ),
    ]
