# Generated by Django 2.1.5 on 2019-08-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0015_auto_20190814_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='level',
            field=models.PositiveIntegerField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='lft',
            field=models.PositiveIntegerField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='rght',
            field=models.PositiveIntegerField(db_index=True, editable=False),
        ),
    ]
