# Generated by Django 2.1.5 on 2019-08-23 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0017_auto_20190821_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='contenttypes.ContentType'),
        ),
    ]
