# Generated by Django 2.1.6 on 2019-09-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0019_auto_20190908_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
