# Generated by Django 2.1.5 on 2019-09-09 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0020_auto_20190908_2130'),
        ('ledger', '0020_auto_20190909_1210'),
    ]

    operations = [
    ]
