# Generated by Django 2.1.5 on 2019-09-24 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0026_auto_20190922_2251'),
        ('ledger', '0026_auto_20190922_1229'),
    ]

    operations = [
    ]
