# Generated by Django 2.1.6 on 2019-09-27 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0026_auto_20190922_1229'),
        ('ledger', '0026_auto_20190922_2251'),
    ]

    operations = [
    ]
