# Generated by Django 2.1.6 on 2019-09-29 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0027_merge_20190927_1144'),
        ('ledger', '0028_auto_20190924_1949'),
        ('ledger', '0027_merge_20190924_1531'),
    ]

    operations = [
    ]
