# Generated by Django 2.1.5 on 2019-10-12 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_auto_20191006_1503'),
        ('ledger', '0029_merge_20190929_1408'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('code', 'company')},
        ),
    ]
