# Generated by Django 2.1.5 on 2019-10-12 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_auto_20191006_1503'),
        ('ledger', '0030_auto_20191012_1545'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('code', 'company')},
        ),
    ]
