# Generated by Django 2.1.5 on 2019-10-12 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0031_auto_20191012_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='ledger.Category'),
            preserve_default=False,
        ),
    ]
