# Generated by Django 2.1.5 on 2019-10-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0032_auto_20191012_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
