# Generated by Django 2.1.5 on 2019-10-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0033_auto_20191012_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
