# Generated by Django 2.1.5 on 2019-10-13 07:39

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0034_auto_20191012_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='default',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='default',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='ledger.Category'),
        ),
    ]
