# Generated by Django 2.1.5 on 2019-11-14 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0036_transactioncharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactioncharge',
            name='account',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_charges', to='ledger.Account'),
        ),
    ]
