# Generated by Django 2.2.6 on 2020-02-04 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0074_auto_20191203_2211'),
        ('ledger', '0037_auto_20191114_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountOpeningBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_balance', models.PositiveIntegerField()),
                ('account', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_opening_balance', to='ledger.Account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_opening_balance', to='company.Company')),
            ],
        ),
    ]
