# Generated by Django 2.1.5 on 2019-12-04 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0074_auto_20191203_2211'),
        ('ledger', '0037_auto_20191114_2318'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='party',
            unique_together={('company', 'tax_registration_number')},
        ),
    ]
