# Generated by Django 2.2.6 on 2020-02-04 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0038_accountopeningbalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountopeningbalance',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_opening_balance', to='ledger.Account'),
        ),
    ]
