# Generated by Django 2.2.6 on 2020-02-04 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0039_auto_20200204_1629'),
        ('ledger', '0039_auto_20200113_2150'),
    ]

    operations = [
    ]
