# Generated by Django 2.1.5 on 2020-02-04 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0075_auto_20200204_1629'),
        ('ledger', '0040_merge_20200204_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountopeningbalance',
            name='opening_balance',
        ),
        migrations.AddField(
            model_name='accountopeningbalance',
            name='fiscal_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='account_opening_balances', to='company.FiscalYear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountopeningbalance',
            name='opening_cr',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountopeningbalance',
            name='opening_dr',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accountopeningbalance',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_opening_balances', to='ledger.Account'),
        ),
        migrations.AlterField(
            model_name='accountopeningbalance',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_opening_balances', to='company.Company'),
        ),
    ]
