# Generated by Django 2.1.5 on 2020-02-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0041_auto_20200204_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountopeningbalance',
            name='opening_cr',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='accountopeningbalance',
            name='opening_dr',
            field=models.FloatField(default=0),
        ),
    ]
