# Generated by Django 2.1.5 on 2020-03-13 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0076_auto_20200302_1539'),
        ('ledger', '0042_auto_20200204_2200'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accountopeningbalance',
            unique_together={('company', 'fiscal_year', 'account')},
        ),
    ]
