# Generated by Django 2.1.5 on 2021-02-18 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0043_auto_20200313_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partyrepresentative',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='representative', to='ledger.Party'),
        ),
    ]
