# Generated by Django 2.1.5 on 2021-05-18 20:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0044_auto_20210218_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=datetime.datetime.now)),
                ('medium', models.CharField(choices=[('Phone', 'Phone'), ('Email', 'Email'), ('SMS', 'SMS'), ('Visit', 'Visit')], default='Phone', max_length=255)),
                ('outbound', models.BooleanField(default=True)),
                ('follow_up', models.DateTimeField(blank=True, null=True)),
                ('followed_up', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Preparing', 'Preparing'), ('Could not Connect', 'Could not Connect'), ('No Response', 'No Response'), ('Could not talk to authority', 'Could not talk to authority'), ('Waiting for Reply', 'Waiting for Reply'), ('Follow Up', 'Follow Up'), ('Fail', 'Fail'), ('Success', 'Success')], max_length=255)),
                ('transcript', models.TextField(blank=True, null=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communication_logs', to='ledger.Party')),
                ('representative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='communication_logs', to='ledger.PartyRepresentative')),
            ],
        ),
    ]
