# Generated by Django 4.1.1 on 2023-06-07 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0082_company_config_template'),
        ('ledger', '0046_auto_20210930_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='company.Company'),
            preserve_default=False,
        ),
    ]
