# Generated by Django 4.2.2 on 2023-06-25 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0082_company_config_template'),
        ('ledger', '0046_auto_20210930_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountClosing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CLOSED', 'CLOSED')], max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_closings', to='company.Company')),
                ('fiscal_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.FiscalYear')),
            ],
        ),
    ]
