# Generated by Django 4.2.2 on 2023-06-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0047_accountclosing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountclosing',
            name='status',
            field=models.CharField(blank=True, choices=[('CLOSED', 'CLOSED')], max_length=50, null=True),
        ),
    ]
