# Generated by Django 4.2.2 on 2023-06-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0048_alter_accountclosing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(default='Regular', max_length=25, verbose_name=(('Regular', 'Regular'), ('Opening', 'Opening'), ('Closing', 'Closing'))),
        ),
    ]
