# Generated by Django 4.2.2 on 2023-06-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0050_journalentry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountclosing',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Closed', 'Closed')], default='Pending', max_length=50),
        ),
    ]
