# Generated by Django 4.2.2 on 2023-06-25 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0051_alter_accountclosing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountclosing',
            name='journal_entry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='account_closings', to='ledger.journalentry'),
            preserve_default=False,
        ),
    ]
