# Generated by Django 4.2.2 on 2023-06-25 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0052_accountclosing_journal_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountclosing',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account_closings', to='ledger.journalentry'),
        ),
    ]
