# Generated by Django 4.1.1 on 2023-06-26 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0047_transaction_company'),
        ('ledger', '0054_alter_accountclosing_journal_entry'),
    ]

    operations = [
    ]
