# Generated by Django 4.2.2 on 2023-06-28 16:55

from django.db import migrations


def set_transaction_company(apps, schema_editor):
    Transaction = apps.get_model('ledger', 'Transaction')
    for transaction in Transaction.objects.all():
        transaction.company_id = transaction.account.company_id
        transaction.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0055_merge_20230626_1524'),
    ]

    operations = [
        migrations.RunPython(set_transaction_company),
    ]
