# Generated by Django 4.1.1 on 2023-06-30 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0056_insert_company_20230628_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partyrepresentative',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representative', to='ledger.party'),
        ),
    ]
