# Generated by Django 4.1.1 on 2023-08-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0057_alter_partyrepresentative_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
