# Generated by Django 4.1.1 on 2023-09-22 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0085_alter_role_modules'),
        ('ledger', '0058_alter_account_default'),
    ]

    operations = [
        # migrations.AlterUniqueTogether(
        #     name='category',
        #     unique_together={('code', 'company'), ('name', 'company')},
        # ),
    ]
