# Generated by Django 4.2.2 on 2023-10-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0059_alter_category_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='source_voucher_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='source_voucher_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
