# Generated by Django 4.2.2 on 2023-10-03 11:11

from django.db import migrations


# TODO Also do this for product/inventory JE
def add_source_fields_to_journal_entry(apps, schema_editor):
    model = apps.get_model('ledger', 'JournalEntry')
    qs = model.objects.all().select_related('content_type')
    count = qs.count()
    for je in qs:
        print(f'{je.id}/{count}')
        content_type_model = je.content_type.model
        content_type_app_label = je.content_type.app_label
        source_id = je.object_id
        try:
            source = apps.get_model(content_type_app_label, content_type_model).objects.get(id=source_id)
        except Exception as e:
            print(e)
            print(f'App: {content_type_app_label} | Model: {content_type_model} | ID: {source_id}')
            continue
        if hasattr(source, 'voucher_id'):
            voucher_id = source.voucher_id
            voucher_no = source.voucher.voucher_no
        else:
            voucher_id = source.id
            try:
                voucher_no = source.voucher_no
            except AttributeError:
                voucher_no = source.id
        je.source_voucher_id = voucher_id
        je.source_voucher_no = voucher_no
        je.save()


class Migration(migrations.Migration):
    dependencies = [
        ('ledger', '0061_rename_source_voucher_number_journalentry_source_voucher_no'),
    ]

    operations = [
        migrations.RunPython(add_source_fields_to_journal_entry),
    ]
