# Generated by Django 4.2.2 on 2023-10-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0062_auto_20231003_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Opening', 'Opening'), ('Closing', 'Closing')], default='Regular', max_length=25),
        ),
    ]
