# Generated by Django 4.1.1 on 2023-11-23 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0064_alter_account_code'),
        ('ledger', '0064_alter_account_options_alter_category_options'),
    ]

    operations = [
    ]
