# Generated by Django 4.1.1 on 2023-11-23 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0064_alter_account_options_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
