# Generated by Django 4.1.1 on 2023-11-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0065_alter_account_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
