# Generated by Django 4.1.1 on 2023-11-23 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0065_merge_20231123_1706'),
        ('ledger', '0066_alter_account_code'),
    ]

    operations = [
    ]
