# Generated by Django 4.2.10 on 2024-09-15 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0067_merge_20231123_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_accounts', to='ledger.account'),
        ),
    ]
