# Generated by Django 4.2.16 on 2024-10-06 07:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0068_account_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='aliases',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
    ]
