# Generated by Django 4.2.16 on 2024-12-03 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('ledger', '0069_party_aliases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_accounts', to='company.company'),
        ),
        migrations.AlterField(
            model_name='accountclosing',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_closings', to='company.company'),
        ),
        migrations.AlterField(
            model_name='accountclosing',
            name='fiscal_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.fiscalyear'),
        ),
        migrations.AlterField(
            model_name='accountopeningbalance',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_opening_balances', to='company.company'),
        ),
        migrations.AlterField(
            model_name='accountopeningbalance',
            name='fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_opening_balances', to='company.fiscalyear'),
        ),
        migrations.AlterField(
            model_name='category',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_categories', to='company.company'),
        ),
        migrations.AlterField(
            model_name='party',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='company.company'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='company.company'),
        ),
        migrations.AlterField(
            model_name='transactioncharge',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
    ]
