# Generated by Django 2.1.5 on 2019-02-08 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ledger', '0002_auto_20190208_1806'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0005_auto_20190208_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesVoucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.PositiveSmallIntegerField()),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('issue_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('transaction_date', models.DateField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Issued', 'Issued'), ('Cancelled', 'Cancelled'), ('Paid', 'Paid')], default='Draft', max_length=15)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('discount', models.FloatField(default=0)),
                ('total_amount', models.FloatField(blank=True, null=True)),
                ('mode', models.CharField(choices=[('Draft', 'Draft'), ('Issued', 'Issued'), ('Cancelled', 'Cancelled'), ('Paid', 'Paid')], default='Party', max_length=15)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_vouchers', to='company.Company')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ledger.Party')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_vouchers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
