# Generated by Django 2.1.5 on 2019-02-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesvoucher',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
