# Generated by Django 4.2.17 on 2025-01-16 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challanrow',
            name='company',
        ),
        migrations.RemoveField(
            model_name='creditnoterow',
            name='company',
        ),
        migrations.RemoveField(
            model_name='debitnoterow',
            name='company',
        ),
        migrations.RemoveField(
            model_name='journalvoucherrow',
            name='company',
        ),
        migrations.RemoveField(
            model_name='purchasevoucherrow',
            name='company',
        ),
        migrations.RemoveField(
            model_name='salesvoucherrow',
            name='company',
        ),
    ]
