# Generated by Django 4.2.17 on 2025-04-11 07:37

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0002_remove_challanrow_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challan',
            name='meta_discount',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='challan',
            name='meta_non_taxable',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='challan',
            name='meta_sub_total',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='challan',
            name='meta_sub_total_after_row_discounts',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='challan',
            name='meta_tax',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='challan',
            name='meta_taxable',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='challanrow',
            name='quantity',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='discount',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='meta_discount',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='meta_non_taxable',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='meta_sub_total',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='meta_sub_total_after_row_discounts',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='meta_tax',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='meta_taxable',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='creditnoterow',
            name='discount',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='creditnoterow',
            name='rate',
            field=models.DecimalField(decimal_places=6, max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='discount',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='meta_discount',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='meta_non_taxable',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='meta_sub_total',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='meta_sub_total_after_row_discounts',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='meta_tax',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='meta_taxable',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='debitnoterow',
            name='discount',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='debitnoterow',
            name='rate',
            field=models.DecimalField(decimal_places=6, max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='journalvoucherrow',
            name='cr_amount',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='journalvoucherrow',
            name='dr_amount',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='amount',
            field=models.DecimalField(decimal_places=6, max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='tds_amount',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='transaction_charge',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='purchasediscount',
            name='value',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='meta_discount',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='meta_non_taxable',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='meta_sub_total',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='meta_sub_total_after_row_discounts',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='meta_tax',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='meta_taxable',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='purchaseorderrow',
            name='quantity',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='purchasevoucher',
            name='discount',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='purchasevoucher',
            name='meta_discount',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='purchasevoucher',
            name='meta_non_taxable',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='purchasevoucher',
            name='meta_sub_total',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='purchasevoucher',
            name='meta_sub_total_after_row_discounts',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='purchasevoucher',
            name='meta_tax',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='purchasevoucher',
            name='meta_taxable',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='purchasevoucher',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='purchasevoucherrow',
            name='discount',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='purchasevoucherrow',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='purchasevoucherrow',
            name='net_amount',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='purchasevoucherrow',
            name='quantity',
            field=models.DecimalField(decimal_places=6, max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='purchasevoucherrow',
            name='rate',
            field=models.DecimalField(decimal_places=6, max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='purchasevoucherrow',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='salesagent',
            name='compensation_multiplier',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='salesdiscount',
            name='value',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='salesvoucher',
            name='discount',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='salesvoucher',
            name='meta_discount',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='salesvoucher',
            name='meta_non_taxable',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='salesvoucher',
            name='meta_sub_total',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='salesvoucher',
            name='meta_sub_total_after_row_discounts',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='salesvoucher',
            name='meta_tax',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='salesvoucher',
            name='meta_taxable',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='salesvoucher',
            name='total_amount',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='salesvoucherrow',
            name='discount',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='salesvoucherrow',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='salesvoucherrow',
            name='net_amount',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='salesvoucherrow',
            name='quantity',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='salesvoucherrow',
            name='rate',
            field=models.DecimalField(decimal_places=6, max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='salesvoucherrow',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
    ]
