# Generated by Django 2.1.5 on 2019-02-10 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0003_taxscheme_default'),
        ('product', '0002_auto_20190208_1906'),
        ('voucher', '0002_salesvoucher_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesVoucherRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('rate', models.FloatField()),
                ('discount', models.FloatField(default=0)),
                ('discount_type', models.CharField(blank=True, choices=[('Amount', 'Amount'), ('Percent', 'Percent')], max_length=15, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Item')),
                ('tax_scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_rows', to='tax.TaxScheme')),
            ],
        ),
        migrations.AddField(
            model_name='salesvoucher',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('Amount', 'Amount'), ('Percent', 'Percent')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='salesvoucherrow',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='voucher.SalesVoucher'),
        ),
    ]
