# Generated by Django 2.1.5 on 2019-03-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0003_auto_20190210_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesvoucher',
            name='mode',
            field=models.CharField(choices=[('Party', 'Party'), ('Cash', 'Cash'), ('eSewa', 'eSewa'), ('Khalti', 'Khalti')], default='Party', max_length=15),
        ),
    ]
