# Generated by Django 4.2.20 on 2025-04-28 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0003_alter_challan_meta_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandedCostRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Duty', 'Duty'), ('Freight', 'Freight'), ('Shipping', 'Shipping'), ('Brokerage', 'Brokerage'), ('Insurance', 'Insurance'), ('Storage', 'Storage'), ('Labour', 'Labour'), ('Regulatory Fee', 'Regulatory Fee'), ('Other', 'Other')], max_length=25)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=6, max_digits=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landed_cost_rows', to='voucher.purchasevoucher')),
            ],
        ),
    ]
