# Generated by Django 2.1.5 on 2019-03-04 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190208_1806'),
        ('ledger', '0006_auto_20190304_1229'),
        ('voucher', '0004_auto_20190301_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditVoucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.PositiveSmallIntegerField()),
                ('date', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('description', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.Party', verbose_name='Receipt From')),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_receipt', to='ledger.Account')),
            ],
        ),
        migrations.CreateModel(
            name='CreditVoucherRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt', models.FloatField()),
                ('discount', models.FloatField(blank=True, null=True)),
                ('cash_receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='voucher.CreditVoucher')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='voucher.SalesVoucher')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='creditvoucherrow',
            unique_together={('invoice', 'cash_receipt')},
        ),
    ]
