# Generated by Django 4.2.20 on 2025-04-29 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0002_alter_taxpayment_amount_alter_taxscheme_rate'),
        ('voucher', '0004_landedcostrow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesvoucherrow',
            name='tax_scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_rows', to='tax.taxscheme'),
        ),
    ]
