# Generated by Django 4.2.20 on 2025-04-30 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0004_landedcostrow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landedcostrow',
            name='type',
            field=models.CharField(choices=[('Duty', 'Duty'), ('Freight', 'Freight'), ('Shipping', 'Shipping'), ('Brokerage', 'Brokerage'), ('Insurance', 'Insurance'), ('Storage', 'Storage'), ('Labour', 'Labour'), ('Regulatory Fee', 'Regulatory Fee'), ('Other', 'Other'), ('Packaging', 'Packaging'), ('Loading', 'Loading'), ('Unloading', 'Unloading')], max_length=25),
        ),
    ]
