# Generated by Django 2.1.5 on 2019-03-05 10:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0006_auto_20190304_1229'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voucher', '0005_auto_20190304_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('short_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BankBranch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='voucher.Bank')),
            ],
        ),
        migrations.CreateModel(
            name='ChequeVoucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheque_no', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField()),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.IntegerField()),
                ('bank_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='voucher.BankBranch')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.Party')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheques', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
