# Generated by Django 4.2.20 on 2025-05-01 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0005_alter_landedcostrow_type'),
        ('voucher', '0005_alter_landedcostrow_type_and_more'),
    ]

    operations = [
    ]
