# Generated by Django 2.1.5 on 2019-03-05 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190208_1806'),
        ('voucher', '0006_bank_bankbranch_chequevoucher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankbranch',
            options={'verbose_name_plural': 'Bank branches'},
        ),
        migrations.AddField(
            model_name='chequevoucher',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.Company'),
            preserve_default=False,
        ),
    ]
