# Generated by Django 2.1.5 on 2019-03-05 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190208_1806'),
        ('voucher', '0007_auto_20190305_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.Company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bankbranch',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.Company'),
            preserve_default=False,
        ),
    ]
