# Generated by Django 4.2.20 on 2025-05-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0007_purchasesetting_require_item_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salessetting',
            name='invoice_footer_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
