# Generated by Django 2.1.5 on 2019-03-07 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190208_1806'),
        ('voucher', '0008_auto_20190305_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design', models.ImageField(upload_to='design/')),
                ('canvas', models.TextField()),
                ('width', models.PositiveSmallIntegerField()),
                ('height', models.PositiveSmallIntegerField()),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
            ],
        ),
    ]
