# Generated by Django 4.2.20 on 2025-05-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0009_alter_landedcostrow_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesvoucher',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
