# Generated by Django 2.1.5 on 2019-03-07 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0009_invoicedesign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedesign',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='company.Company'),
        ),
    ]
