# Generated by Django 4.2.20 on 2025-05-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0010_salesvoucher_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasesetting',
            name='enable_discount_in_voucher',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='salessetting',
            name='enable_discount_in_voucher',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='salessetting',
            name='enable_reference_in_voucher',
            field=models.BooleanField(default=False),
        ),
    ]
