# Generated by Django 2.1.5 on 2019-03-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0010_auto_20190307_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesvoucher',
            name='mode',
            field=models.CharField(choices=[('Party', 'Party'), ('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Credit', 'Credit'), ('eSewa', 'eSewa'), ('Khalti', 'Khalti')], default='Party', max_length=15),
        ),
    ]
