# Generated by Django 4.2.20 on 2025-05-08 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0004_quotation_reference'),
        ('voucher', '0011_purchasesetting_enable_discount_in_voucher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesvoucher',
            name='quotation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_invoice', to='quotation.quotation'),
        ),
    ]
