# Generated by Django 2.1.5 on 2019-03-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0011_auto_20190308_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesvoucherrow',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
