# Generated by Django 4.2.20 on 2025-05-06 10:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0012_landedcostrow_credit_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landedcostrow',
            name='tax_amount',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=24),
        ),
        migrations.AddField(
            model_name='landedcostrow',
            name='total_amount',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=24),
        ),
    ]
