# Generated by Django 4.2.20 on 2025-05-13 12:26

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0012_salesvoucher_quotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challanrow',
            name='quantity',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))]),
        ),
        migrations.AlterField(
            model_name='purchaseorderrow',
            name='quantity',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))]),
        ),
        migrations.AlterField(
            model_name='purchasevoucherrow',
            name='quantity',
            field=models.DecimalField(decimal_places=6, max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))]),
        ),
        migrations.AlterField(
            model_name='salesvoucherrow',
            name='quantity',
            field=models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))]),
        ),
    ]
