# Generated by Django 2.1.5 on 2019-03-14 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0012_salesvoucherrow_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(blank=True, max_length=150, null=True)),
                ('account_number', models.CharField(max_length=150)),
                ('bank_name', models.CharField(blank=True, max_length=250, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='salesvoucher',
            name='epayment',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salesvoucher',
            name='mode',
            field=models.CharField(choices=[('Credit', 'Credit'), ('Cash', 'Cash'), ('Cheque', 'Cheque'), ('ePayment', 'ePayment'), ('Bank Deposit', 'Bank Deposit')], default='Credit', max_length=15),
        ),
        migrations.AddField(
            model_name='salesvoucher',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voucher.BankAccount'),
        ),
    ]
