# Generated by Django 4.2.20 on 2025-05-15 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0012_salesvoucher_quotation'),
        ('voucher', '0013_landedcostrow_tax_amount_landedcostrow_total_amount'),
    ]

    operations = [
    ]
