# Generated by Django 2.1.5 on 2019-03-15 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20190311_1321'),
        ('voucher', '0013_auto_20190314_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='company.Company'),
            preserve_default=False,
        ),
    ]
