# Generated by Django 2.1.5 on 2019-03-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0014_bankaccount_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditvoucher',
            name='sale_vouchers',
            field=models.ManyToManyField(related_name='credit_notes', to='voucher.SalesVoucher'),
        ),
    ]
