# Generated by Django 4.2.20 on 2025-05-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0014_merge_20250515_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landedcostrow',
            name='type',
            field=models.CharField(choices=[('Duty', 'Duty'), ('Labor', 'Labor'), ('Freight', 'Freight'), ('Insurance', 'Insurance'), ('Brokerage', 'Brokerage'), ('Storage', 'Storage'), ('Packaging', 'Packaging'), ('Loading', 'Loading'), ('Unloading', 'Unloading'), ('Regulatory Fee', 'Regulatory Fee'), ('Customs Declaration', 'Customs Declaration'), ('Other Charges', 'Other Charges'), ('Tax on Purchase', 'Tax On Purchase')], max_length=25),
        ),
    ]
