# Generated by Django 4.2.20 on 2025-05-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0014_merge_20250515_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesvoucher',
            name='tax_type',
            field=models.CharField(choices=[('Tax Exclusive', 'Tax Exclusive'), ('Tax Inclusive', 'Tax Inclusive'), ('No Tax', 'No Tax')], default='Tax Exclusive', max_length=15),
        ),
    ]
