# Generated by Django 4.2.20 on 2025-05-20 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_alter_account_current_cr_alter_account_current_dr_and_more'),
        ('voucher', '0015_alter_landedcostrow_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landedcostrow',
            name='credit_account',
            field=models.ForeignKey(blank=True, help_text='Account to which the landed cost will be credited', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='landed_cost_rows', to='ledger.account'),
        ),
        migrations.AlterField(
            model_name='landedcostrow',
            name='type',
            field=models.CharField(choices=[('Duty', 'Duty'), ('Labor', 'Labor'), ('Freight', 'Freight'), ('Insurance', 'Insurance'), ('Brokerage', 'Brokerage'), ('Storage', 'Storage'), ('Packaging', 'Packaging'), ('Loading', 'Loading'), ('Unloading', 'Unloading'), ('Regulatory Fee', 'Regulatory Fee'), ('Customs Declaration', 'Customs Declaration'), ('Other Charges', 'Other Charges'), ('Tax on Purchase', 'Tax On Purchase'), ('Customs Valuation Uplift', 'Customs Valuation Uplift')], max_length=25),
        ),
    ]
