# Generated by Django 2.1.5 on 2019-03-26 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0004_auto_20190303_1548'),
        ('voucher', '0015_creditvoucher_sale_vouchers'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditvoucherrow',
            name='tax_scheme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='credit_rows', to='tax.TaxScheme'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='creditvoucherrow',
            unique_together=set(),
        ),
    ]
