# Generated by Django 2.1.5 on 2019-03-26 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_item_discount_ledger'),
        ('voucher', '0016_auto_20190326_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditvoucherrow',
            name='invoice',
        ),
        migrations.AddField(
            model_name='creditvoucherrow',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.Item'),
            preserve_default=False,
        ),
    ]
