# Generated by Django 4.2.20 on 2025-05-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0016_alter_landedcostrow_credit_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landedcostrow',
            name='is_percentage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='landedcostrow',
            name='value',
            field=models.DecimalField(decimal_places=6, max_digits=24),
        ),
    ]
