# Generated by Django 4.2.20 on 2025-06-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0017_landedcostrow_is_percentage_landedcostrow_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesvoucher',
            name='received_by',
            field=models.TextField(blank=True, null=True),
        ),
    ]
