# Generated by Django 2.1.5 on 2019-03-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0017_auto_20190326_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditvoucherrow',
            name='credit_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
