# Generated by Django 2.1.5 on 2019-03-31 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0018_creditvoucherrow_credit_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditvoucherrow',
            name='receipt',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
