# Generated by Django 4.2.20 on 2025-06-02 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0018_salesvoucher_received_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='salessetting',
            name='enable_received_by_in_voucher',
            field=models.BooleanField(default=False),
        ),
    ]
