# Generated by Django 2.1.5 on 2019-03-31 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0019_auto_20190331_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditvoucherrow',
            name='receipt',
        ),
    ]
