# Generated by Django 4.2.20 on 2025-06-02 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0015_salesvoucher_tax_type'),
        ('voucher', '0019_salessetting_enable_received_by_in_voucher'),
    ]

    operations = [
    ]
