# Generated by Django 4.2.20 on 2025-06-02 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0013_alter_challanrow_quantity_and_more'),
        ('voucher', '0020_merge_20250602_1503'),
    ]

    operations = [
    ]
