# Generated by Django 2.1.5 on 2019-06-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0021_journalvoucher_journalvoucherrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankbranch',
            name='cheque_prefix',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='bankbranch',
            name='current_cheque_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bankbranch',
            name='start_cheque_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
