# Generated by Django 4.2.20 on 2025-06-03 10:56

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0022_purchasesetting_update_cost_price_with_landed_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasevoucher',
            name='meta_fixed_assets_tax',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AddField(
            model_name='purchasevoucher',
            name='meta_fixed_assets_taxable',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AddField(
            model_name='purchasevoucher',
            name='meta_import_tax_excl_fixed_assets',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AddField(
            model_name='purchasevoucher',
            name='meta_import_taxable_excl_fixed_assets',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
    ]
