# Generated by Django 2.1.5 on 2019-06-04 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0022_auto_20190604_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankbranch',
            name='start_cheque_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
