# Generated by Django 4.2.20 on 2025-06-04 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0023_purchasevoucher_meta_fixed_assets_tax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasevoucher',
            name='import_country',
            field=models.CharField(blank=True, help_text='Country of import', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchasevoucher',
            name='import_date',
            field=models.DateField(blank=True, help_text='Date of import', null=True),
        ),
        migrations.AddField(
            model_name='purchasevoucher',
            name='import_document_number',
            field=models.CharField(blank=True, help_text='Document number of import', max_length=100, null=True),
        ),
    ]
