# Generated by Django 4.2.20 on 2025-06-05 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0024_purchasevoucher_import_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salessetting',
            name='enable_remarks_in_voucher',
            field=models.BooleanField(default=True),
        ),
    ]
