# Generated by Django 4.2.20 on 2025-06-12 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0025_salessetting_enable_remarks_in_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasesetting',
            name='enable_expense_type_in_voucher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchasevoucher',
            name='expense_type',
            field=models.CharField(choices=[('Purchase/Expense', 'Purchase/Expense'), ('Capital Expense', 'Capital Expense')], default='Purchase/Expense', max_length=50),
        ),
    ]
