# Generated by Django 2.1.5 on 2019-06-04 09:22

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0009_partyrepresentative_name'),
        ('users', '0022_auto_20190603_1605'),
        ('voucher', '0025_auto_20190604_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChequeDeposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.IntegerField()),
                ('date', models.DateField()),
                ('clearing_date', models.DateField(default=datetime.datetime(2019, 6, 4, 9, 22, 19, 302650, tzinfo=utc))),
                ('deposited_by', models.CharField(blank=True, max_length=254, null=True)),
                ('narration', models.TextField(blank=True, null=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheque_deposits', to='ledger.Account')),
                ('benefactor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.Account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
            ],
        ),
        migrations.CreateModel(
            name='ChequeDepositRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.IntegerField()),
                ('cheque_number', models.CharField(blank=True, max_length=50, null=True)),
                ('cheque_date', models.DateField(blank=True, default=datetime.datetime(2019, 6, 4, 9, 22, 19, 303366, tzinfo=utc), null=True)),
                ('drawee_bank', models.CharField(blank=True, max_length=254, null=True)),
                ('drawee_bank_address', models.CharField(blank=True, max_length=254, null=True)),
                ('amount', models.FloatField()),
                ('cheque_deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='voucher.ChequeDeposit')),
            ],
        ),
    ]
