# Generated by Django 2.1.5 on 2019-06-04 09:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0026_chequedeposit_chequedepositrow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequedeposit',
            name='clearing_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='chequedepositrow',
            name='cheque_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
