# Generated by Django 4.2.20 on 2025-06-12 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0026_purchasesetting_enable_expense_type_in_voucher_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasesetting',
            old_name='enable_expense_type_in_voucher',
            new_name='enable_type_in_voucher',
        ),
        migrations.RenameField(
            model_name='purchasevoucher',
            old_name='expense_type',
            new_name='type',
        ),
    ]
