# Generated by Django 4.2.20 on 2025-06-25 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0027_rename_enable_expense_type_in_voucher_purchasesetting_enable_type_in_voucher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landedcostrow',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('INR', 'INR'), ('NPR', 'NPR')], default='USD', max_length=3),
        ),
    ]
