# Generated by Django 2.1.5 on 2019-06-04 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0027_auto_20190604_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chequedepositrow',
            name='sn',
        ),
    ]
