# Generated by Django 2.1.5 on 2019-06-09 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_unit'),
        ('voucher', '0028_remove_chequedepositrow_sn'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesvoucherrow',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Unit'),
        ),
    ]
