# Generated by Django 4.2.20 on 2025-06-25 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0028_landedcostrow_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasesetting',
            name='round_up_additional_costs',
            field=models.BooleanField(default=False),
        ),
    ]
