# Generated by Django 2.1.5 on 2019-06-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0029_salesvoucherrow_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequedepositrow',
            name='cheque_number',
            field=models.CharField(default='000000', max_length=50),
            preserve_default=False,
        ),
    ]
