# Generated by Django 2.1.5 on 2019-06-09 11:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0030_auto_20190609_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequedepositrow',
            name='cheque_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='chequedepositrow',
            name='drawee_bank',
            field=models.CharField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chequedepositrow',
            name='drawee_bank_address',
            field=models.CharField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
