# Generated by Django 2.1.5 on 2019-06-10 08:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0009_partyrepresentative_name'),
        ('users', '0024_auto_20190609_1256'),
        ('product', '0008_item_unit'),
        ('tax', '0005_auto_20190522_1524'),
        ('voucher', '0031_auto_20190609_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseVoucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.PositiveIntegerField(blank=True, null=True)),
                ('credit', models.BooleanField(default=False)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('tax', models.CharField(blank=True, choices=[('no', 'No Tax'), ('inclusive', 'Tax Inclusive'), ('exclusive', 'Tax Exclusive')], default='inclusive', max_length=10, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('pending_amount', models.FloatField(blank=True, null=True)),
                ('total_amount', models.FloatField(blank=True, null=True)),
                ('discount', models.FloatField(default=0)),
                ('discount_type', models.CharField(blank=True, choices=[('Amount', 'Amount'), ('Percent', 'Percent')], max_length=15, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ledger.Party')),
                ('tax_scheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tax.TaxScheme')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseVoucherRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sn', models.PositiveIntegerField()),
                ('quantity', models.FloatField()),
                ('rate', models.FloatField()),
                ('discount', models.FloatField(default=0)),
                ('discount_type', models.CharField(blank=True, choices=[('Amount', 'Amount'), ('Percent', 'Percent')], max_length=15, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='product.Item')),
                ('tax_scheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tax.TaxScheme')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Unit')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='voucher.PurchaseVoucher')),
            ],
        ),
        migrations.AlterField(
            model_name='salesvoucherrow',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Unit'),
        ),
    ]
