# Generated by Django 2.1.5 on 2019-06-10 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0032_auto_20190610_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasevoucher',
            name='party',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ledger.Party'),
            preserve_default=False,
        ),
    ]
