# Generated by Django 2.1.5 on 2019-06-11 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0033_auto_20190610_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasevoucherrow',
            name='sn',
        ),
    ]
