# Generated by Django 2.1.5 on 2019-06-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0034_remove_purchasevoucherrow_sn'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasevoucherrow',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
