# Generated by Django 2.1.5 on 2019-06-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0035_purchasevoucherrow_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasevoucher',
            name='tax',
            field=models.CharField(blank=True, choices=[('No Tax', 'No Tax'), ('Tax Inclusive', 'Tax Inclusive'), ('Tax Exclusive', 'Tax Exclusive')], default='inclusive', max_length=10, null=True),
        ),
    ]
