# Generated by Django 2.1.5 on 2019-07-25 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0010_remove_party_account'),
        ('voucher', '0036_auto_20190611_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='ledger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_accounts', to='ledger.Account'),
        ),
        migrations.AlterField(
            model_name='salesvoucher',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Issued', 'Issued'), ('Cancelled', 'Cancelled'), ('Paid', 'Paid'), ('Partially Paid', 'Partially Paid')], default='Draft', max_length=15),
        ),
    ]
