# Generated by Django 2.1.5 on 2019-07-29 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0037_auto_20190725_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='company',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='ledger',
        ),
        migrations.AlterField(
            model_name='salesvoucher',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank.BankAccount'),
        ),
        migrations.DeleteModel(
            name='BankAccount',
        ),
    ]
