# Generated by Django 2.1.5 on 2019-07-29 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0038_auto_20190729_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chequedeposit',
            name='bank_account',
        ),
        migrations.RemoveField(
            model_name='chequedeposit',
            name='benefactor',
        ),
        migrations.RemoveField(
            model_name='chequedeposit',
            name='company',
        ),
        migrations.RemoveField(
            model_name='chequedepositrow',
            name='cheque_deposit',
        ),
        migrations.DeleteModel(
            name='ChequeDeposit',
        ),
        migrations.DeleteModel(
            name='ChequeDepositRow',
        ),
    ]
