# Generated by Django 2.1.5 on 2019-08-12 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0039_auto_20190729_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='company',
        ),
        migrations.RemoveField(
            model_name='bankbranch',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='bankbranch',
            name='company',
        ),
        migrations.RemoveField(
            model_name='chequevoucher',
            name='bank_branch',
        ),
        migrations.RemoveField(
            model_name='chequevoucher',
            name='company',
        ),
        migrations.RemoveField(
            model_name='chequevoucher',
            name='party',
        ),
        migrations.RemoveField(
            model_name='chequevoucher',
            name='user',
        ),
        migrations.DeleteModel(
            name='Bank',
        ),
        migrations.DeleteModel(
            name='BankBranch',
        ),
        migrations.DeleteModel(
            name='ChequeVoucher',
        ),
    ]
