# Generated by Django 2.1.5 on 2019-08-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0040_auto_20190812_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(choices=[('Amount', 'Amount'), ('Percent', 'Percent')], max_length=25)),
                ('value', models.FloatField()),
                ('trade_discount', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalesDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(choices=[('Amount', 'Amount'), ('Percent', 'Percent')], max_length=25)),
                ('value', models.FloatField()),
                ('trade_discount', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
