# Generated by Django 2.1.5 on 2019-08-17 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20190812_1846'),
        ('voucher', '0041_purchasediscount_salesdiscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasediscount',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_discounts', to='company.Company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesdiscount',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sales_discounts', to='company.Company'),
            preserve_default=False,
        ),
    ]
