# Generated by Django 2.1.5 on 2019-08-20 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0042_auto_20190817_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesvoucher',
            name='sale_discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voucher.SalesDiscount'),
        ),
    ]
