# Generated by Django 2.1.5 on 2019-08-25 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20190822_1640'),
        ('voucher', '0043_salesvoucher_sale_discount'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='creditvoucher',
            unique_together={('company', 'voucher_no')},
        ),
        migrations.AlterUniqueTogether(
            name='journalvoucher',
            unique_together={('company', 'voucher_no')},
        ),
        migrations.AlterUniqueTogether(
            name='purchasevoucher',
            unique_together={('company', 'voucher_no')},
        ),
        migrations.AlterUniqueTogether(
            name='salesvoucher',
            unique_together={('company', 'voucher_no')},
        ),
    ]
