# Generated by Django 2.1.5 on 2019-08-26 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0044_auto_20190825_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesvoucherrow',
            name='sale_discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_rows', to='voucher.SalesDiscount'),
        ),
    ]
