# Generated by Django 2.1.5 on 2019-08-26 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0045_salesvoucherrow_sale_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesvoucherrow',
            old_name='sale_discount',
            new_name='discount_obj',
        ),
        migrations.RemoveField(
            model_name='salesvoucher',
            name='sale_discount',
        ),
        migrations.AddField(
            model_name='salesvoucher',
            name='discount_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='voucher.SalesDiscount'),
        ),
    ]
