# Generated by Django 2.1.6 on 2019-08-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0046_auto_20190827_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasevoucher',
            name='mode',
            field=models.CharField(choices=[('Credit', 'Credit'), ('Cash', 'Cash'), ('Cheque', 'Cheque'), ('ePayment', 'ePayment'), ('Bank Deposit', 'Bank Deposit')], default='Credit', max_length=15),
        ),
    ]
