# Generated by Django 2.1.6 on 2019-08-28 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_bankaccount_short_name'),
        ('voucher', '0047_purchasevoucher_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasevoucher',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank.BankAccount'),
        ),
    ]
