# Generated by Django 2.1.6 on 2019-08-28 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0048_purchasevoucher_bank_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasevoucher',
            name='discount_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase', to='voucher.PurchaseDiscount'),
        ),
    ]
