# Generated by Django 2.1.6 on 2019-08-28 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voucher', '0049_purchasevoucher_discount_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasevoucher',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_vouchers', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
