# Generated by Django 2.1.6 on 2019-08-28 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0050_purchasevoucher_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasevoucherrow',
            name='discount_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_rows', to='voucher.PurchaseDiscount'),
        ),
    ]
