# Generated by Django 2.1.6 on 2019-08-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0051_purchasevoucherrow_discount_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasevoucher',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Issued', 'Issued'), ('Cancelled', 'Cancelled'), ('Paid', 'Paid'), ('Partially Paid', 'Partially Paid')], default='Draft', max_length=15),
        ),
    ]
