# Generated by Django 2.1.5 on 2019-08-29 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0052_purchasevoucher_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasevoucher',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='purchasevoucher',
            name='pending_amount',
        ),
        migrations.RemoveField(
            model_name='purchasevoucher',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='purchasevoucher',
            name='tax_scheme',
        ),
        migrations.RemoveField(
            model_name='purchasevoucher',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='salesvoucher',
            name='total_amount',
        ),
        migrations.AlterField(
            model_name='purchasevoucher',
            name='discount_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='voucher.PurchaseDiscount'),
        ),
    ]
