# Generated by Django 2.1.5 on 2019-08-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0053_auto_20190829_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesvoucher',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='salesvoucher',
            name='print_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
