# Generated by Django 2.1.5 on 2019-09-03 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_auto_20190903_1527'),
        ('voucher', '0054_auto_20190829_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesvoucher',
            name='fiscal_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sale_vouchers', to='company.FiscalYear'),
            preserve_default=False,
        ),
    ]
