# Generated by Django 2.1.5 on 2019-09-03 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_auto_20190903_1527'),
        ('voucher', '0055_salesvoucher_fiscal_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesvoucher',
            name='voucher_no',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='purchasevoucher',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='salesvoucher',
            unique_together={('company', 'voucher_no', 'fiscal_year')},
        ),
    ]
