# Generated by Django 2.1.5 on 2019-09-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0056_auto_20190903_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasevoucher',
            name='is_import',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesvoucher',
            name='is_export',
            field=models.BooleanField(default=False),
        ),
    ]
