# Generated by Django 2.1.5 on 2019-09-05 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0057_auto_20190904_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasevoucher',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
