# Generated by Django 2.1.5 on 2019-09-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0058_purchasevoucher_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasevoucher',
            name='voucher_no',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
