# Generated by Django 2.1.5 on 2019-09-06 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0018_auto_20190823_1540'),
        ('users', '0037_auto_20190906_1158'),
        ('voucher', '0059_auto_20190905_1200'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreditVoucher',
            new_name='CreditNote',
        ),
        migrations.AlterField(
            model_name='creditvoucherrow',
            name='tax_scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_row', to='tax.TaxScheme'),
        ),
    ]
