# Generated by Django 2.1.5 on 2019-09-06 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0005_auto_20190522_1524'),
        ('product', '0033_auto_20190823_1540'),
        ('voucher', '0060_auto_20190906_1158'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreditVoucherRow',
            new_name='CreditNoteRow',
        ),
    ]
