# Generated by Django 2.1.5 on 2019-09-06 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_auto_20190823_1540'),
        ('bank', '0004_bankaccount_short_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0037_auto_20190906_1158'),
        ('voucher', '0061_auto_20190906_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditnoterow',
            old_name='cash_receipt',
            new_name='voucher',
        ),
        migrations.RemoveField(
            model_name='creditnoterow',
            name='credit_amount',
        ),
        migrations.AddField(
            model_name='creditnote',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank.BankAccount'),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='discount_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_note', to='voucher.SalesDiscount'),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('Amount', 'Amount'), ('Percent', 'Percent')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='fiscal_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='credit_note', to='company.FiscalYear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditnote',
            name='mode',
            field=models.CharField(choices=[('Credit', 'Credit'), ('Cash', 'Cash'), ('Cheque', 'Cheque'), ('ePayment', 'ePayment'), ('Bank Deposit', 'Bank Deposit')], default='Credit', max_length=15),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='credit_note', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditnoterow',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditnoterow',
            name='discount_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_rows', to='voucher.SalesDiscount'),
        ),
        migrations.AddField(
            model_name='creditnoterow',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('Amount', 'Amount'), ('Percent', 'Percent')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='creditnoterow',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='creditnoterow',
            name='rate',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditnoterow',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Unit'),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ledger.Party', verbose_name='Receipt From'),
        ),
        migrations.AlterField(
            model_name='creditnoterow',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='creditnoterow',
            name='tax_scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_rows', to='tax.TaxScheme'),
        ),
    ]
