# Generated by Django 2.1.5 on 2019-09-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0062_auto_20190906_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditnote',
            name='reference',
        ),
        migrations.AddField(
            model_name='creditnote',
            name='remarks',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
