# Generated by Django 2.1.5 on 2019-09-06 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0063_auto_20190906_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditnote',
            name='description',
        ),
        migrations.RemoveField(
            model_name='creditnote',
            name='remarks',
        ),
    ]
