# Generated by Django 2.1.5 on 2019-09-06 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0064_auto_20190906_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='remarks',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
