# Generated by Django 2.1.5 on 2019-09-06 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0065_creditnote_remarks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditnote',
            old_name='sale_vouchers',
            new_name='invoices',
        ),
        migrations.AlterField(
            model_name='salesvoucher',
            name='fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_vouchers', to='company.FiscalYear'),
        ),
    ]
