# Generated by Django 2.1.5 on 2019-09-06 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0066_auto_20190906_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditnote',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='creditnote',
            name='receipt',
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='discount_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes', to='voucher.SalesDiscount'),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_notes', to='company.FiscalYear'),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ledger.Party'),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
