# Generated by Django 2.1.5 on 2019-09-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0067_auto_20190906_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Issued', 'Issued'), ('Cancelled', 'Cancelled'), ('Resolved', 'Resolved')], default='Draft', max_length=25),
        ),
    ]
