# Generated by Django 2.1.5 on 2019-09-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0068_creditnote_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnote',
            name='voucher_no',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
