# Generated by Django 2.1.5 on 2019-09-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0069_auto_20190906_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='print_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
