# Generated by Django 2.1.5 on 2019-09-08 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_auto_20190908_1648'),
        ('voucher', '0071_auto_20190908_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasevoucher',
            name='fiscal_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_vouchers', to='company.FiscalYear'),
            preserve_default=False,
        ),
    ]
