# Generated by Django 2.1.6 on 2019-09-09 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0072_purchasevoucher_fiscal_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasevoucher',
            name='fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_vouchers', to='company.FiscalYear'),
        ),
    ]
