# Generated by Django 2.1.5 on 2019-09-09 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0073_auto_20190909_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasevoucher',
            name='fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_vouchers', to='company.FiscalYear'),
        ),
    ]
