# Generated by Django 2.1.5 on 2019-09-09 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0074_auto_20190909_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnoterow',
            name='is_returned',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='debitnoterow',
            name='is_returned',
            field=models.BooleanField(default=True),
        ),
    ]
