# Generated by Django 2.1.5 on 2019-09-09 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_auto_20190909_1652'),
        ('voucher', '0075_auto_20190909_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesvoucher',
            name='epayment',
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='mode',
            field=models.CharField(choices=[('Credit', 'Credit'), ('Cash', 'Cash'), ('Bank Deposit', 'Bank Deposit')], default='Credit', max_length=15),
        ),
        migrations.AlterField(
            model_name='creditnoterow',
            name='discount_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_note_rows', to='voucher.SalesDiscount'),
        ),
        migrations.AlterField(
            model_name='creditnoterow',
            name='tax_scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_note_rows', to='tax.TaxScheme'),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='mode',
            field=models.CharField(choices=[('Credit', 'Credit'), ('Cash', 'Cash'), ('Bank Deposit', 'Bank Deposit')], default='Credit', max_length=15),
        ),
        migrations.AlterField(
            model_name='debitnoterow',
            name='discount_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debit_note_rows', to='voucher.PurchaseDiscount'),
        ),
        migrations.AlterField(
            model_name='debitnoterow',
            name='tax_scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_note_rows', to='tax.TaxScheme'),
        ),
        migrations.AlterField(
            model_name='purchasevoucher',
            name='mode',
            field=models.CharField(choices=[('Credit', 'Credit'), ('Cash', 'Cash'), ('Bank Deposit', 'Bank Deposit')], default='Credit', max_length=15),
        ),
        migrations.AlterField(
            model_name='salesvoucher',
            name='mode',
            field=models.CharField(choices=[('Credit', 'Credit'), ('Cash', 'Cash'), ('Bank Deposit', 'Bank Deposit')], default='Credit', max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='creditnote',
            unique_together={('company', 'voucher_no', 'fiscal_year')},
        ),
        migrations.AlterUniqueTogether(
            name='debitnote',
            unique_together={('company', 'voucher_no', 'fiscal_year')},
        ),
    ]
