# Generated by Django 2.1.5 on 2019-09-09 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0076_auto_20190909_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesvoucher',
            old_name='transaction_date',
            new_name='date',
        ),
    ]
