# Generated by Django 2.1.5 on 2019-09-09 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0077_auto_20190909_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalvoucherrow',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_voucher_rows', to='ledger.Account'),
        ),
    ]
