# Generated by Django 2.1.5 on 2019-09-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0078_auto_20190909_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('compensation_multiplier', models.FloatField(default=1)),
            ],
        ),
    ]
