# Generated by Django 2.1.5 on 2019-09-13 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0079_salesagent'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesvoucher',
            name='sales_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_invoices', to='voucher.SalesAgent'),
        ),
        migrations.AlterField(
            model_name='salesvoucher',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_invoices', to='company.Company'),
        ),
        migrations.AlterField(
            model_name='salesvoucher',
            name='fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_invoices', to='company.FiscalYear'),
        ),
        migrations.AlterField(
            model_name='salesvoucher',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_invoices', to=settings.AUTH_USER_MODEL),
        ),
    ]
