# Generated by Django 2.1.5 on 2019-09-13 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_company_enable_sales_agents'),
        ('voucher', '0080_auto_20190913_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesagent',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sales_agents', to='company.Company'),
            preserve_default=False,
        ),
    ]
