# Generated by Django 2.1.5 on 2019-09-13 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0081_salesagent_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='total_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='total_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasevoucher',
            name='total_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesvoucher',
            name='total_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
