# Generated by Django 2.1.5 on 2019-10-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0082_auto_20190914_0416'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnote',
            name='trade_discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='trade_discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchasevoucher',
            name='trade_discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesvoucher',
            name='trade_discount',
            field=models.BooleanField(default=False),
        ),
    ]
