# Generated by Django 2.1.5 on 2019-10-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0083_auto_20191001_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnoterow',
            name='trade_discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='debitnoterow',
            name='trade_discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchasevoucherrow',
            name='trade_discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesvoucherrow',
            name='trade_discount',
            field=models.BooleanField(default=False),
        ),
    ]
