# Generated by Django 2.1.5 on 2019-10-01 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_auto_20191001_2044'),
        ('bank', '0018_merge_20190929_1408'),
        ('voucher', '0084_auto_20191001_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_trade_discount_in_voucher', models.BooleanField(default=False)),
                ('show_trade_discount_in_row', models.BooleanField(default=False)),
                ('mode', models.CharField(default='Credit', max_length=15)),
                ('enable_row_description', models.BooleanField(default=False)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank.BankAccount')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_setting', to='company.Company')),
            ],
        ),
        migrations.CreateModel(
            name='SalesSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_party_by_default', models.BooleanField(default=True)),
                ('show_trade_discount_in_voucher', models.BooleanField(default=False)),
                ('show_trade_discount_in_row', models.BooleanField(default=False)),
                ('mode', models.CharField(default='Credit', max_length=15)),
                ('enable_row_description', models.BooleanField(default=False)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank.BankAccount')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales_setting', to='company.Company')),
            ],
        ),
    ]
