# Generated by Django 2.1.5 on 2019-10-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0085_purchasesetting_salessetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasesetting',
            name='is_trade_discount_in_row',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchasesetting',
            name='is_trade_discount_in_voucher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salessetting',
            name='is_trade_discount_in_row',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salessetting',
            name='is_trade_discount_in_voucher',
            field=models.BooleanField(default=False),
        ),
    ]
