# Generated by Django 2.1.5 on 2019-11-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0086_auto_20191002_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasevoucher',
            name='voucher_no',
            field=models.CharField(max_length=25),
        ),
    ]
