# Generated by Django 2.1.6 on 2019-11-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0087_auto_20191103_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasesetting',
            name='hide_due_date_in_voucher',
            field=models.BooleanField(default=False),
        ),
    ]
