# Generated by Django 2.1.6 on 2019-11-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0088_purchasesetting_hide_due_date_in_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='salessetting',
            name='hide_due_date_in_voucher',
            field=models.BooleanField(default=False),
        ),
    ]
