# Generated by Django 2.1.6 on 2019-11-08 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0089_salessetting_hide_due_date_in_voucher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchasesetting',
            old_name='hide_due_date_in_voucher',
            new_name='enable_due_date_in_voucher',
        ),
        migrations.RenameField(
            model_name='salessetting',
            old_name='hide_due_date_in_voucher',
            new_name='enable_due_date_in_voucher',
        ),
    ]
