# Generated by Django 2.1.5 on 2019-11-11 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0090_auto_20191108_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesvoucherrow',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_rows', to='product.Item'),
        ),
    ]
