# Generated by Django 2.1.5 on 2019-11-12 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0091_auto_20191112_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesvoucherrow',
            name='discount_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesvoucherrow',
            name='tax_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
