# Generated by Django 2.1.5 on 2019-11-12 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0092_auto_20191112_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesvoucherrow',
            name='net_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
