# Generated by Django 2.1.5 on 2019-11-14 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0036_transactioncharge'),
        ('bank', '0021_auto_20191031_1537'),
        ('voucher', '0093_salesvoucherrow_net_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mode', models.CharField(choices=[('Cheque', 'Cheque'), ('Cash', 'Cash'), ('Bank Deposit', 'Bank Deposit')], default='Cheque', max_length=15)),
                ('transaction_charge', models.FloatField(default=0)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_receipts', to='bank.BankAccount')),
                ('cheque_deposit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_receipts', to='bank.ChequeDeposit')),
                ('invoices', models.ManyToManyField(related_name='payment_receipts', to='voucher.SalesVoucher')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_receipts', to='ledger.Party')),
                ('transaction_charge_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_receipts', to='ledger.TransactionCharge')),
            ],
        ),
    ]
