# Generated by Django 2.1.5 on 2019-11-14 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0072_auto_20191114_2318'),
        ('voucher', '0094_paymentreceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreceipt',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='company.Company'),
            preserve_default=False,
        ),
    ]
