# Generated by Django 2.1.5 on 2019-11-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0095_paymentreceipt_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreceipt',
            name='cleared',
            field=models.BooleanField(default=False),
        ),
    ]
