# Generated by Django 2.1.5 on 2019-11-14 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0096_paymentreceipt_cleared'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreceipt',
            name='amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
