# Generated by Django 2.1.5 on 2019-11-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0097_paymentreceipt_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentreceipt',
            name='cleared',
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='status',
            field=models.CharField(choices=[('Issued', 'Issued'), ('Cleared', 'Cleared'), ('Cancelled', 'Cancelled')], default='Issued', max_length=20),
        ),
    ]
