# Generated by Django 2.1.5 on 2019-11-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0098_auto_20191115_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreceipt',
            name='clearing_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
