# Generated by Django 2.1.5 on 2019-11-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0099_paymentreceipt_clearing_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreceipt',
            name='tds_amount',
            field=models.FloatField(default=0),
        ),
    ]
