# Generated by Django 2.1.5 on 2019-12-04 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0074_auto_20191203_2211'),
        ('voucher', '0100_paymentreceipt_tds_amount'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salesagent',
            unique_together={('name', 'company')},
        ),
    ]
