# Generated by Django 2.1.5 on 2020-03-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0101_auto_20191204_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasevoucherrow',
            name='discount_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasevoucherrow',
            name='net_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasevoucherrow',
            name='tax_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
