# Generated by Django 2.2.6 on 2020-03-02 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0046_auto_20200227_1934'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ledger', '0042_auto_20200204_2200'),
        ('users', '0075_auto_20200204_1629'),
        ('voucher', '0102_auto_20200301_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('issue_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Issued', 'Issued'), ('Cancelled', 'Cancelled'), ('Paid', 'Paid'), ('Partially Paid', 'Partially Paid')], default='Draft', max_length=15)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_export', models.BooleanField(default=False)),
                ('print_count', models.PositiveSmallIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challan', to='company.Company')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challan', to='company.FiscalYear')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ledger.Party')),
                ('sales_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challan', to='voucher.SalesAgent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challan', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChallanRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('rate', models.FloatField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challan_rows', to='product.Item')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Unit')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='voucher.Challan')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
