# Generated by Django 2.2.6 on 2020-03-02 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0103_challan_challanrow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challanrow',
            name='rate',
        ),
    ]
