# Generated by Django 2.2.6 on 2020-03-02 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0104_remove_challanrow_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challan',
            name='is_export',
        ),
    ]
