# Generated by Django 2.2.6 on 2020-03-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0076_auto_20200302_1539'),
        ('voucher', '0105_remove_challan_is_export'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesvoucher',
            name='challan',
            field=models.ManyToManyField(related_name='sales', to='voucher.Challan'),
        ),
        migrations.AlterUniqueTogether(
            name='challan',
            unique_together={('company', 'voucher_no', 'fiscal_year')},
        ),
        migrations.RemoveField(
            model_name='challan',
            name='status',
        ),
    ]
