# Generated by Django 2.2.6 on 2020-03-03 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0106_auto_20200303_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesvoucher',
            old_name='challan',
            new_name='challans',
        ),
    ]
