# Generated by Django 2.2.6 on 2020-03-04 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0107_auto_20200303_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesvoucher',
            name='challans',
            field=models.ManyToManyField(blank=True, related_name='sales', to='voucher.Challan'),
        ),
    ]
