# Generated by Django 2.2.6 on 2020-03-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0108_auto_20200304_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='salessetting',
            name='enable_import_challan',
            field=models.BooleanField(default=False),
        ),
    ]
