# Generated by Django 2.1.5 on 2020-11-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0109_salessetting_enable_import_challan'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesvoucher',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
