# Generated by Django 2.1.5 on 2021-01-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0110_salesvoucher_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='challan',
            name='meta_discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='challan',
            name='meta_non_taxable',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='challan',
            name='meta_sub_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='challan',
            name='meta_sub_total_after_row_discounts',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='challan',
            name='meta_tax',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='challan',
            name='meta_taxable',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='meta_discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='meta_non_taxable',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='meta_sub_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='meta_sub_total_after_row_discounts',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='meta_tax',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='meta_taxable',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='meta_discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='meta_non_taxable',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='meta_sub_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='meta_sub_total_after_row_discounts',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='meta_tax',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='meta_taxable',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasevoucher',
            name='meta_discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasevoucher',
            name='meta_non_taxable',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasevoucher',
            name='meta_sub_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasevoucher',
            name='meta_sub_total_after_row_discounts',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasevoucher',
            name='meta_tax',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasevoucher',
            name='meta_taxable',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesvoucher',
            name='meta_discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesvoucher',
            name='meta_non_taxable',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesvoucher',
            name='meta_sub_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesvoucher',
            name='meta_sub_total_after_row_discounts',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesvoucher',
            name='meta_tax',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesvoucher',
            name='meta_taxable',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
