# Generated by Django 2.1.5 on 2021-02-18 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0111_auto_20210129_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challan',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.Party'),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.Party'),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.Party'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_receipts', to='ledger.Party'),
        ),
        migrations.AlterField(
            model_name='purchasevoucher',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ledger.Party'),
        ),
        migrations.AlterField(
            model_name='salesvoucher',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.Party'),
        ),
    ]
