# Generated by Django 4.1.1 on 2022-09-07 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0046_auto_20210930_1822'),
        ('voucher', '0112_auto_20210218_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesvoucher',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='ledger.party'),
        ),
    ]
