# Generated by Django 4.1.1 on 2022-09-14 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0051_alter_category_extra_fields_alter_item_extra_data'),
        ('voucher', '0113_alter_salesvoucher_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasevoucherrow',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_rows', to='product.item'),
        ),
        migrations.AlterField(
            model_name='purchasevoucherrow',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_rows', to='product.unit'),
        ),
        migrations.AlterField(
            model_name='salesvoucherrow',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_rows', to='product.unit'),
        ),
    ]
