# Generated by Django 4.1.1 on 2023-08-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0114_alter_purchasevoucherrow_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challan',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Issued', 'Issued'), ('Cancelled', 'Cancelled')], default='Draft', max_length=255),
            preserve_default=False,
        ),
    ]
