# Generated by Django 4.1.1 on 2023-08-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0115_challan_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challan',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Issued', 'Issued'), ('Cancelled', 'Cancelled'), ('Resolved', 'Resolved')], max_length=255),
        ),
    ]
