# Generated by Django 4.1.1 on 2023-08-30 05:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0084_alter_role_modules'),
        ('product', '0051_alter_category_extra_fields_alter_item_extra_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ledger', '0058_alter_account_default'),
        ('voucher', '0116_alter_challan_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_sub_total', models.FloatField(blank=True, null=True)),
                ('meta_sub_total_after_row_discounts', models.FloatField(blank=True, null=True)),
                ('meta_discount', models.FloatField(blank=True, null=True)),
                ('meta_non_taxable', models.FloatField(blank=True, null=True)),
                ('meta_taxable', models.FloatField(blank=True, null=True)),
                ('meta_tax', models.FloatField(blank=True, null=True)),
                ('voucher_no', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('issue_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Issued', 'Issued'), ('Resolved', 'Resolved'), ('Cancelled', 'Cancelled')], max_length=255)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('print_count', models.PositiveSmallIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_Orders', to='company.Company')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='company.FiscalYear')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.party')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('company', 'voucher_no', 'fiscal_year')},
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_order_rows', to='product.item')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.unit')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='voucher.purchaseorder')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
