# Generated by Django 4.1.1 on 2023-08-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0117_purchaseorder_purchaseorderrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasesetting',
            name='enable_purchase_order_import',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('Issued', 'Issued'), ('Cancelled', 'Cancelled')], max_length=255),
        ),
    ]
