# Generated by Django 4.1.1 on 2023-08-30 10:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0118_purchasesetting_enable_purchase_order_import_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasesetting',
            name='enable_item_rate_change_alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchasesetting',
            name='rate_change_alert_emails',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(blank=True, max_length=254, null=True), blank=True, null=True, size=None),
        ),
    ]
