# Generated by Django 4.1.1 on 2023-09-01 05:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0121_alter_purchasesetting_rate_change_alert_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasesetting',
            name='rate_change_alert_emails',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(blank=True, max_length=254), blank=True, default=list, size=None),
        ),
    ]
