# Generated by Django 4.1.1 on 2023-09-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0123_alter_purchasesetting_rate_change_alert_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='salessetting',
            name='enable_amount_entry',
            field=models.BooleanField(default=False),
        ),
    ]
