# Generated by Django 4.1.1 on 2023-09-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0124_salessetting_enable_amount_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesvoucher',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
