# Generated by Django 4.1.1 on 2023-09-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0125_salesvoucher_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='salessetting',
            name='show_rate_quantity_in_voucher',
            field=models.BooleanField(default=True),
        ),
    ]
