# Generated by Django 4.1.1 on 2023-09-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0126_salessetting_show_rate_quantity_in_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='salessetting',
            name='invoice_footer_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
