# Generated by Django 4.1.1 on 2023-09-13 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0085_alter_role_modules'),
        ('voucher', '0127_salessetting_invoice_footer_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_fifo', models.BooleanField(default=False)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_setting', to='company.Company')),
            ],
        ),
    ]
