# Generated by Django 4.1.1 on 2023-09-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0128_inventorysetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorysetting',
            name='enable_negative_stock_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchasevoucherrow',
            name='remaining_quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
