# Generated by Django 4.1.1 on 2023-09-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0129_inventorysetting_enable_negative_stock_check_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesvoucherrow',
            name='sold_items',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
