# Generated by Django 4.1.1 on 2023-10-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0130_salesvoucherrow_sold_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='challanrow',
            name='sold_items',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
