# Generated by Django 4.1.1 on 2023-09-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0130_salesvoucherrow_sold_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='salessetting',
            name='persist_pos_items',
            field=models.BooleanField(default=False),
        ),
    ]
