# Generated by Django 4.1.1 on 2023-10-11 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0131_salessetting_persist_pos_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='salessetting',
            name='enable_sales_date_edit',
            field=models.BooleanField(default=False),
        ),
    ]
