# Generated by Django 4.1.1 on 2023-11-23 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0132_salessetting_enable_sales_date_edit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesagent',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='salesagent',
            name='compensation_multiplier',
            field=models.FloatField(),
        ),
    ]
