# Generated by Django 4.1.1 on 2023-10-15 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0131_challanrow_sold_items'),
        ('voucher', '0132_salessetting_enable_sales_date_edit'),
    ]

    operations = [
    ]
