# Generated by Django 4.1.1 on 2023-11-03 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0132_salessetting_enable_sales_date_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasesetting',
            name='enable_empty_voucher_no',
            field=models.BooleanField(default=False),
        ),
    ]
