# Generated by Django 4.1.1 on 2023-11-23 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0133_alter_salesagent_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchasediscount',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='salesdiscount',
            options={'ordering': ['-id']},
        ),
    ]
