# Generated by Django 4.1.1 on 2023-10-15 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0133_merge_20231015_1456'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InventorySetting',
        ),
    ]
