# Generated by Django 4.1.1 on 2023-11-03 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0133_purchasesetting_enable_empty_voucher_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasevoucher',
            name='voucher_no',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
