# Generated by Django 4.1.1 on 2023-11-23 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0133_alter_salesagent_options_and_more'),
        ('voucher', '0134_alter_purchasevoucher_voucher_no'),
    ]

    operations = [
    ]
