# Generated by Django 4.1.1 on 2023-11-05 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0134_alter_purchasevoucher_voucher_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesagent',
            options={'ordering': ['-id']},
        ),
    ]
