# Generated by Django 4.1.1 on 2023-12-03 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0133_purchasesetting_enable_empty_voucher_no'),
        ('voucher', '0134_alter_purchasediscount_options_and_more'),
    ]

    operations = [
    ]
