# Generated by Django 4.1.1 on 2023-11-23 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0134_delete_inventorysetting'),
        ('voucher', '0135_alter_salesagent_options'),
        ('voucher', '0135_merge_20231123_1703'),
    ]

    operations = [
    ]
