# Generated by Django 4.1.1 on 2023-12-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0135_merge_20231203_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasevoucher',
            name='purchase_orders',
            field=models.ManyToManyField(blank=True, related_name='purchases', to='voucher.purchaseorder'),
        ),
    ]
