# Generated by Django 4.1.1 on 2023-12-26 07:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("voucher", "0134_delete_inventorysetting"),
        ("voucher", "0136_purchasevoucher_purchase_orders"),
    ]

    operations = []
