# Generated by Django 4.1.1 on 2023-12-17 05:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("voucher", "0134_alter_purchasevoucher_voucher_no"),
        ("voucher", "0136_purchasevoucher_purchase_orders"),
    ]

    operations = []
