# Generated by Django 4.1.1 on 2023-11-23 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0134_alter_purchasediscount_options_and_more'),
        ('voucher', '0136_merge_20231123_1707'),
    ]

    operations = [
    ]
