# Generated by Django 4.1.1 on 2024-01-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voucher", "0137_merge_20231226_1303"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchasevoucher",
            name="voucher_no",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
