# Generated by Django 4.1.1 on 2023-12-03 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0135_merge_20231203_1530'),
        ('voucher', '0137_merge_20231123_1759'),
    ]

    operations = [
    ]
