# Generated by Django 4.1.1 on 2024-01-07 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voucher", "0138_alter_purchasevoucher_voucher_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="debitnoterow",
            name="purchase_row_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
