# Generated by Django 4.1.1 on 2023-12-03 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0136_purchasevoucher_purchase_orders'),
        ('voucher', '0138_merge_20231203_1701'),
    ]

    operations = [
    ]
