# Generated by Django 4.1.1 on 2023-12-25 05:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("voucher", "0137_merge_20231217_1130"),
        ("voucher", "0139_merge_20231203_1702"),
    ]

    operations = []
