# Generated by Django 4.1.1 on 2024-01-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voucher", "0139_debitnoterow_purchase_row_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="debitnoterow",
            name="purchase_row_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
