# Generated by Django 4.1.1 on 2023-12-31 10:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("voucher", "0137_merge_20231226_1303"),
        ("voucher", "0140_merge_20231225_1108"),
    ]

    operations = []
