# Generated by Django 4.1.1 on 2024-01-09 15:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("voucher", "0140_alter_debitnoterow_purchase_row_data"),
        ("voucher", "0141_merge_20231231_1642"),
    ]

    operations = []
