# Generated by Django 4.1.1 on 2024-01-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0142_merge_20240109_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnoterow',
            name='sales_row_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
