# Generated by Django 4.2.9 on 2024-02-08 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0143_creditnoterow_sales_row_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challanrow',
            name='sold_items',
        ),
        migrations.RemoveField(
            model_name='creditnoterow',
            name='sales_row_data',
        ),
        migrations.RemoveField(
            model_name='salesvoucherrow',
            name='sold_items',
        ),
    ]
