# Generated by Django 4.2.9 on 2024-02-08 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0144_remove_challanrow_sold_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasevoucherrow',
            name='remaining_quantity',
        ),
    ]
