# Generated by Django 4.2.10 on 2024-02-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0145_remove_purchasevoucherrow_remaining_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnoterow',
            name='sales_row_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
