# Generated by Django 4.1.1 on 2024-02-21 11:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0089_remove_company_email_company_emails'),
        ('voucher', '0146_creditnoterow_sales_row_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAdjustmentVoucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.PositiveIntegerField(blank=True, null=True)),
                ('date', models.DateField()),
                ('issue_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Issued', 'Issued'), ('Cancelled', 'Cancelled')], max_length=225)),
                ('company', models.ManyToManyField(related_name='stock_adjustment_voucher', to='company.Company')),
            ],
        ),
    ]
