# Generated by Django 4.1.1 on 2024-02-22 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0089_remove_company_email_company_emails'),
        ('voucher', '0147_stockadjustmentvoucher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockadjustmentvoucher',
            name='company',
        ),
        migrations.AddField(
            model_name='stockadjustmentvoucher',
            name='company',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustment_voucher', to='company.Company'),
            preserve_default=False,
        ),
    ]
