# Generated by Django 4.2.10 on 2024-02-23 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0077_remove_inventoryaccount_opening_quantity'),
        ('voucher', '0148_remove_stockadjustmentvoucher_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjustmentvoucher',
            name='purpose',
            field=models.CharField(choices=[('Stock In', 'Stock In'), ('Stock Out', 'Stock Out'), ('Damaged', 'Damaged')], default=1, max_length=225),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockadjustmentvoucher',
            name='remarks',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='StockAdjustmentVoucherRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustment_rows', to='product.item')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.unit')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='voucher.stockadjustmentvoucher')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
