# Generated by Django 4.2.10 on 2024-02-27 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0149_stockadjustmentvoucher_purpose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockadjustmentvoucher',
            name='purpose',
            field=models.CharField(choices=[('Stock In', 'Stock In'), ('Stock Out', 'Stock Out'), ('Damaged', 'Damaged'), ('Expired', 'Expired')], max_length=225),
        ),
    ]
