# Generated by Django 4.2.10 on 2024-02-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0151_stockadjustmentvoucher_meta_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockadjustmentvoucher',
            name='total_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
