# Generated by Django 4.2.10 on 2024-03-10 06:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0081_remove_billofmaterialrow_rate'),
        ('users', '0091_alter_role_modules'),
        ('voucher', '0152_stockadjustmentvoucher_total_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryConversionVoucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.PositiveIntegerField(blank=True, null=True)),
                ('date', models.DateField()),
                ('issue_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Issued', 'Issued'), ('Cancelled', 'Cancelled')], max_length=225)),
                ('remarks', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_conversion_voucher', to='company.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryConversionVoucherRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('transaction_type', models.CharField(blank=True, choices=[('Cr', 'Cr'), ('Dr', 'Dr')], max_length=16, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_conversion_voucher_rows', to='product.item')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.unit')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='voucher.inventoryconversionvoucher')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
