# Generated by Django 4.2.10 on 2024-03-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0153_inventoryconversionvoucher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryconversionvoucher',
            name='meta_discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryconversionvoucher',
            name='meta_non_taxable',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryconversionvoucher',
            name='meta_sub_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryconversionvoucher',
            name='meta_sub_total_after_row_discounts',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryconversionvoucher',
            name='meta_tax',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryconversionvoucher',
            name='meta_taxable',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
