# Generated by Django 4.2.10 on 2024-03-11 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0081_remove_billofmaterialrow_rate'),
        ('voucher', '0154_inventoryconversionvoucher_meta_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryconversionvoucher',
            name='finished_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_conversion_voucher', to='product.billofmaterial'),
        ),
    ]
