# Generated by Django 4.2.10 on 2024-03-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0155_inventoryconversionvoucher_finished_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryconversionvoucherrow',
            name='rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
