# Generated by Django 4.2.10 on 2024-03-12 06:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0093_alter_role_modules'),
        ('product', '0081_remove_billofmaterialrow_rate'),
        ('voucher', '0156_alter_inventoryconversionvoucherrow_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAdjustmentVoucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_sub_total', models.FloatField(blank=True, null=True)),
                ('meta_sub_total_after_row_discounts', models.FloatField(blank=True, null=True)),
                ('meta_discount', models.FloatField(blank=True, null=True)),
                ('meta_non_taxable', models.FloatField(blank=True, null=True)),
                ('meta_taxable', models.FloatField(blank=True, null=True)),
                ('meta_tax', models.FloatField(blank=True, null=True)),
                ('voucher_no', models.PositiveIntegerField(blank=True, null=True)),
                ('date', models.DateField()),
                ('issue_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Issued', 'Issued'), ('Cancelled', 'Cancelled')], max_length=225)),
                ('purpose', models.CharField(choices=[('Stock In', 'Stock In'), ('Stock Out', 'Stock Out'), ('Damaged', 'Damaged'), ('Expired', 'Expired')], max_length=225)),
                ('remarks', models.TextField()),
                ('total_amount', models.FloatField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_adjustment_voucher', to='company.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryAdjustmentVoucherRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_adjustment_rows', to='product.item')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.unit')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='voucher.inventoryadjustmentvoucher')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='stockadjustmentvoucherrow',
            name='item',
        ),
        migrations.RemoveField(
            model_name='stockadjustmentvoucherrow',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='stockadjustmentvoucherrow',
            name='voucher',
        ),
        migrations.DeleteModel(
            name='StockAdjustmentVoucher',
        ),
        migrations.DeleteModel(
            name='StockAdjustmentVoucherRow',
        ),
    ]
