# Generated by Django 4.2.10 on 2024-08-30 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0157_inventoryadjustmentvoucher_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryadjustmentvoucherrow',
            name='item',
        ),
        migrations.RemoveField(
            model_name='inventoryadjustmentvoucherrow',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='inventoryadjustmentvoucherrow',
            name='voucher',
        ),
        migrations.RemoveField(
            model_name='inventoryconversionvoucher',
            name='company',
        ),
        migrations.RemoveField(
            model_name='inventoryconversionvoucher',
            name='finished_product',
        ),
        migrations.RemoveField(
            model_name='inventoryconversionvoucherrow',
            name='item',
        ),
        migrations.RemoveField(
            model_name='inventoryconversionvoucherrow',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='inventoryconversionvoucherrow',
            name='voucher',
        ),
        migrations.DeleteModel(
            name='InventoryAdjustmentVoucher',
        ),
        migrations.DeleteModel(
            name='InventoryAdjustmentVoucherRow',
        ),
        migrations.DeleteModel(
            name='InventoryConversionVoucher',
        ),
        migrations.DeleteModel(
            name='InventoryConversionVoucherRow',
        ),
    ]
