# Generated by Django 4.2.16 on 2024-11-14 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0095_alter_role_modules'),
        ('ledger', '0069_party_aliases'),
        ('voucher', '0158_remove_inventoryadjustmentvoucherrow_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnote',
            name='mode',
            field=models.CharField(blank=True, choices=[('Credit', 'Credit'), ('Cash', 'Cash'), ('Bank Deposit', 'Bank Deposit')], default='Credit', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='mode',
            field=models.CharField(blank=True, choices=[('Credit', 'Credit'), ('Cash', 'Cash'), ('Bank Deposit', 'Bank Deposit')], default='Credit', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='purchasevoucher',
            name='mode',
            field=models.CharField(blank=True, choices=[('Credit', 'Credit'), ('Cash', 'Cash'), ('Bank Deposit', 'Bank Deposit')], default='Credit', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='salesvoucher',
            name='mode',
            field=models.CharField(blank=True, choices=[('Credit', 'Credit'), ('Cash', 'Cash'), ('Bank Deposit', 'Bank Deposit')], default='Credit', max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='PaymentMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('enabled_for_sales', models.BooleanField(default=True)),
                ('enabled_for_purchase', models.BooleanField(default=True)),
                ('transaction_fee_config', models.JSONField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_modes', to='ledger.account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
                ('transaction_fee_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_mode_transaction_fee', to='ledger.account')),
            ],
        ),
        migrations.AddField(
            model_name='creditnote',
            name='payment_mode',
            field=models.ForeignKey(blank=True, help_text='Payment mode for this credit note. Null means it is not paid (credit).', null=True, on_delete=django.db.models.deletion.PROTECT, to='voucher.paymentmode'),
        ),
        migrations.AddField(
            model_name='debitnote',
            name='payment_mode',
            field=models.ForeignKey(blank=True, help_text='Payment mode for this debit note. Null means it is not paid (credit).', null=True, on_delete=django.db.models.deletion.PROTECT, to='voucher.paymentmode'),
        ),
        migrations.AddField(
            model_name='purchasesetting',
            name='payment_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_setting', to='voucher.paymentmode'),
        ),
        migrations.AddField(
            model_name='purchasevoucher',
            name='payment_mode',
            field=models.ForeignKey(blank=True, help_text='Payment mode for this purchase. Null means it is not paid (credit).', null=True, on_delete=django.db.models.deletion.PROTECT, to='voucher.paymentmode'),
        ),
        migrations.AddField(
            model_name='salessetting',
            name='payment_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_setting', to='voucher.paymentmode'),
        ),
        migrations.AddField(
            model_name='salesvoucher',
            name='payment_mode',
            field=models.ForeignKey(blank=True, help_text='Payment mode for this sales invoice. Null means it is not paid (credit).', null=True, on_delete=django.db.models.deletion.PROTECT, to='voucher.paymentmode'),
        ),
    ]
