# Generated by Django 4.2.16 on 2024-12-03 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('voucher', '0160_auto_20241114_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challan',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challan', to='company.company'),
        ),
        migrations.AlterField(
            model_name='challan',
            name='fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challan', to='company.fiscalyear'),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
        migrations.AlterField(
            model_name='creditnote',
            name='fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_notes', to='company.fiscalyear'),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
        migrations.AlterField(
            model_name='debitnote',
            name='fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_notes', to='company.fiscalyear'),
        ),
        migrations.AlterField(
            model_name='invoicedesign',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='company.company'),
        ),
        migrations.AlterField(
            model_name='journalvoucher',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
        migrations.AlterField(
            model_name='paymentmode',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
        migrations.AlterField(
            model_name='purchasediscount',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_discounts', to='company.company'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_Orders', to='company.company'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='company.fiscalyear'),
        ),
        migrations.AlterField(
            model_name='purchasesetting',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_setting', to='company.company'),
        ),
        migrations.AlterField(
            model_name='purchasevoucher',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
        migrations.AlterField(
            model_name='purchasevoucher',
            name='fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_vouchers', to='company.fiscalyear'),
        ),
        migrations.AlterField(
            model_name='salesagent',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_agents', to='company.company'),
        ),
        migrations.AlterField(
            model_name='salesdiscount',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_discounts', to='company.company'),
        ),
        migrations.AlterField(
            model_name='salessetting',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales_setting', to='company.company'),
        ),
        migrations.AlterField(
            model_name='salesvoucher',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_invoices', to='company.company'),
        ),
        migrations.AlterField(
            model_name='salesvoucher',
            name='fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_invoices', to='company.fiscalyear'),
        ),
    ]
