# Generated by Django 2.1.5 on 2019-09-13 17:50

import apps.aggregator.widgets
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('widget', models.CharField(choices=[('Sales By Agent', 'Sales By Agent')], max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('day_count', models.PositiveSmallIntegerField(default=7)),
                ('display_type', models.CharField(choices=[('Table', 'Table'), ('Bar', 'Bar'), ('Line', 'Line'), ('Scatter', 'Scatter'), ('Axis-mixed', 'Axis-mixed'), ('Pie', 'Pie'), ('Percentage', 'Percentage'), ('Heatmap', 'Heatmap')], default='Table', max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
