# Generated by Django 2.1.5 on 2019-09-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='widget',
            field=models.CharField(choices=[('Sales By Agent', 'Sales By Agent')], max_length=255),
        ),
    ]
