# Generated by Django 2.1.5 on 2019-09-13 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0002_auto_20190913_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='widget',
            field=models.CharField(choices=[('Sales Count by Party', 'Sales Count by Party')], max_length=255),
        ),
    ]
