# Generated by Django 2.1.5 on 2019-09-13 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0003_auto_20190914_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='widget',
            name='widget',
            field=models.CharField(choices=[('Sales Amount by Party', 'Sales Amount by Party'), ('Sales Amount by Agent', 'Sales Amount by Agent'), ('Sales Count by Agent', 'Sales Count by Agent'), ('Sales Count by Party', 'Sales Count by Party')], max_length=255),
        ),
    ]
