# Generated by Django 2.1.5 on 2019-09-14 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0004_auto_20190914_0447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='widget',
            old_name='day_count',
            new_name='count',
        ),
    ]
