# Generated by Django 2.1.5 on 2019-09-14 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0005_auto_20190914_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='group_by',
            field=models.CharField(choices=[('Day', 'Day'), ('Week', 'Week'), ('Month', 'Month'), ('Year', 'Year')], default='Day', max_length=10),
        ),
    ]
