# Generated by Django 2.1.5 on 2019-09-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0006_widget_group_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
