# Generated by Django 2.1.5 on 2019-09-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0007_widget_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='group_by',
            field=models.CharField(choices=[('Day', 'Day'), ('Month', 'Month'), ('Year', 'Year')], default='Day', max_length=10),
        ),
    ]
