# Generated by Django 2.1.5 on 2019-09-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0008_auto_20190915_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='group_by',
            field=models.CharField(choices=[('Day', 'Day(s)'), ('Month', 'Month(s)'), ('Year', 'Year(s)')], default='Day', max_length=10),
        ),
    ]
