# Generated by Django 2.1.5 on 2019-09-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0009_auto_20190915_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='display_type',
            field=models.CharField(choices=[('Table', 'Table'), ('Bar', 'Bar'), ('Line', 'Line'), ('Radar', 'Radar'), ('Pie', 'Pie'), ('Doughnut', 'Doughnut'), ('Polar Area', 'Polar Area'), ('Mixed', 'Mixed')], default='Table', max_length=255),
        ),
    ]
