# Generated by Django 2.1.5 on 2019-09-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0010_auto_20190915_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='group_by',
            field=models.CharField(choices=[('Day', 'Day(s)'), ('Week', 'Week(s)'), ('Month', 'Month(s)'), ('Year', 'Year(s)')], default='Day', max_length=10),
        ),
    ]
