# Generated by Django 2.1.6 on 2019-11-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0011_auto_20190916_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='widget',
            field=models.CharField(choices=[('Sales Amount by Party', 'Sales Amount by Party'), ('Sales Amount by Agent', 'Sales Amount by Agent'), ('Sales Count by Agent', 'Sales Count by Agent'), ('Sales Count by Party', 'Sales Count by Party'), ('Purchase Count by Party', 'Purchase Count by Party'), ('Total Purchase Amount', 'Total Purchase Amount'), ('Total Sales Amount', 'Total Sales Amount'), ('Sales Count by Mode', 'Sales Count by Mode'), ('Purchase Count by Mode', 'Purchase Count by Mode')], max_length=255),
        ),
    ]
