# Generated by Django 4.1.1 on 2023-11-23 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aggregator', '0012_auto_20191106_1134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='widget',
            options={'ordering': ['-id']},
        ),
    ]
