// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AccountList: typeof import('./src/components/account/AccountList.vue')['default']
    BalanceSheetTableNode: typeof import('./src/components/report/BalanceSheetTableNode.vue')['default']
    BsDatePicker: typeof import('./src/components/date/BsDatePicker.vue')['default']
    ChallanTable: typeof import('./src/components/challan/ChallanTable.vue')['default']
    ChartsView: typeof import('./src/components/charts/ChartsView.vue')['default']
    DateInputDisabled: typeof import('./src/components/date/DateInputDisabled.vue')['default']
    DatePicker: typeof import('./src/components/date/DatePicker.vue')['default']
    DateRangePicker: typeof import('./src/components/date/DateRangePicker.vue')['default']
    EmailList: typeof import('./src/components/settings/EmailList.vue')['default']
    EssentialLink: typeof import('./src/components/EssentialLink.vue')['default']
    ExampleComponent: typeof import('./src/components/ExampleComponent.vue')['default']
    FiltersOptions: typeof import('./src/components/report/FiltersOptions.vue')['default']
    InvoiceRow: typeof import('./src/components/voucher/InvoiceRow.vue')['default']
    InvoiceTable: typeof import('./src/components/voucher/InvoiceTable.vue')['default']
    ItemImport: typeof import('./src/components/ItemImport.vue')['default']
    ItemMergeGroup: typeof import('./src/components/settings/ItemMergeGroup.vue')['default']
    LoginCard: typeof import('./src/components/LoginCard.vue')['default']
    MultiSelectChip: typeof import('./src/components/filter/MultiSelectChip.vue')['default']
    NAutoComplete: typeof import('./src/components/NAutoComplete.vue')['default']
    PaginateList: typeof import('./src/components/core/PaginateList.vue')['default']
    PieChart: typeof import('./src/components/report/PieChart.vue')['default']
    PlainNode: typeof import('./src/components/report/PlainNode.vue')['default']
    PosInvoiceTable: typeof import('./src/components/pos/PosInvoiceTable.vue')['default']
    PrintHeader: typeof import('./src/components/print/PrintHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectItemAccountsWithTypes: typeof import('./src/components/SelectItemAccountsWithTypes.vue')['default']
    SelectWithFetch: typeof import('./src/components/SelectWithFetch.vue')['default']
    TableNode: typeof import('./src/components/report/TableNode.vue')['default']
    TablePagination: typeof import('./src/components/account/TablePagination.vue')['default']
    TransactionTable: typeof import('./src/components/account/TransactionTable.vue')['default']
    ViewerHeader: typeof import('./src/components/viewer/ViewerHeader.vue')['default']
    ViewerTable: typeof import('./src/components/viewer/ViewerTable.vue')['default']
    VoucherRow: typeof import('./src/components/VoucherRow.vue')['default']
  }
}
