// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    EssentialLink: typeof import('./src/components/EssentialLink.vue')['default']
    ExampleComponent: typeof import('./src/components/ExampleComponent.vue')['default']
    Header: typeof import('./src/components/viewer/ViewerHeader.vue')['default']
    InvoiceRow: typeof import('./src/components/voucher/InvoiceRow.vue')['default']
    InvoiceTable: typeof import('./src/components/voucher/InvoiceTable.vue')['default']
    LoginCard: typeof import('./src/components/LoginCard.vue')['default']
    NAutoComplete: typeof import('./src/components/NAutoComplete.vue')['default']
    PrintHeader: typeof import('./src/components/print/PrintHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SalesVoucherPrint: typeof import('./src/components/print/SalesVoucherPrint.vue')['default']
    ViewerHeader: typeof import('./src/components/viewer/ViewerHeader.vue')['default']
    ViewerTable: typeof import('./src/components/viewer/ViewerTable.vue')['default']
  }
}
