# Generated by Django 4.2.16 on 2024-12-31 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_wallet', models.BooleanField(default=False)),
                ('account_name', models.CharField(blank=True, max_length=150, null=True)),
                ('account_number', models.CharField(blank=True, max_length=150, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=250, null=True)),
                ('short_name', models.CharField(blank=True, max_length=250, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=250, null=True)),
                ('next_cheque_no', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_commission_percent', models.FloatField(blank=True, default=0, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BankCashDeposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.IntegerField(blank=True, default=None, null=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Cleared', 'Cleared'), ('Cancelled', 'Cancelled')], default='Cleared', max_length=25)),
                ('amount', models.FloatField()),
                ('deposited_by', models.CharField(blank=True, max_length=255, null=True)),
                ('narration', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChequeDeposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Issued', 'Issued'), ('Cleared', 'Cleared'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20)),
                ('date', models.DateField()),
                ('clearing_date', models.DateField(blank=True, null=True)),
                ('cheque_number', models.CharField(blank=True, max_length=50, null=True)),
                ('cheque_date', models.DateField(blank=True, null=True)),
                ('drawee_bank', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.FloatField()),
                ('deposited_by', models.CharField(blank=True, max_length=255, null=True)),
                ('narration', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChequeIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheque_no', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField()),
                ('issued_to', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.FloatField()),
                ('status', models.CharField(choices=[('Issued', 'Issued'), ('Cancelled', 'Cancelled')], default='Issued', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='FundTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('transaction_fee', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Issued', 'Issued'), ('Cancelled', 'Cancelled')], default='Issued', max_length=25)),
                ('narration', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FundTransferTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('transaction_fee', models.FloatField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
    ]
