# Generated by Django 2.1.5 on 2019-07-29 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0026_auto_20190725_1704'),
        ('ledger', '0012_auto_20190729_1309'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(blank=True, max_length=150, null=True)),
                ('account_number', models.CharField(max_length=150)),
                ('bank_name', models.CharField(blank=True, max_length=250, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=250, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='company.Company')),
                ('ledger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_accounts', to='ledger.Account')),
            ],
        ),
    ]
