# Generated by Django 4.2.17 on 2025-01-15 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('is_wallet', models.BooleanField(default=False)),
                ('account_name', models.CharField(blank=True, max_length=150, null=True)),
                ('account_number', models.CharField(blank=True, max_length=150, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=250, null=True)),
                ('short_name', models.CharField(blank=True, max_length=250, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=250, null=True)),
                ('next_cheque_no', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_commission_percent', models.FloatField(blank=True, default=0, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='BankCashDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('voucher_no', models.IntegerField(blank=True, default=None, null=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Cleared', 'Cleared'), ('Cancelled', 'Cancelled')], default='Cleared', max_length=25)),
                ('amount', models.FloatField()),
                ('deposited_by', models.CharField(blank=True, max_length=255, null=True)),
                ('narration', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChequeDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('voucher_no', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Issued', 'Issued'), ('Cleared', 'Cleared'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20)),
                ('date', models.DateField()),
                ('clearing_date', models.DateField(blank=True, null=True)),
                ('cheque_number', models.CharField(blank=True, max_length=50, null=True)),
                ('cheque_date', models.DateField(blank=True, null=True)),
                ('drawee_bank', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.FloatField()),
                ('deposited_by', models.CharField(blank=True, max_length=255, null=True)),
                ('narration', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChequeIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('cheque_no', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField()),
                ('issued_to', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.FloatField()),
                ('status', models.CharField(choices=[('Issued', 'Issued'), ('Cancelled', 'Cancelled')], default='Issued', max_length=25)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FundTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('voucher_no', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('transaction_fee', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Issued', 'Issued'), ('Cancelled', 'Cancelled')], default='Issued', max_length=25)),
                ('narration', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FundTransferTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('name', models.CharField(max_length=255)),
                ('transaction_fee', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReconciliationRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Reconciled', 'Reconciled'), ('Matched', 'Matched'), ('Unreconciled', 'Unreconciled')], default='Reconciled', max_length=20)),
                ('date', models.DateField()),
                ('dr_amount', models.FloatField(blank=True, null=True)),
                ('cr_amount', models.FloatField(blank=True, null=True)),
                ('balance', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adjustment_amount', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReconciliationRowTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_last_updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ReconciliationStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
