# Generated by Django 2.1.5 on 2019-07-29 07:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20190725_1704'),
        ('ledger', '0012_auto_20190729_1309'),
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChequeDeposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.IntegerField()),
                ('date', models.DateField()),
                ('clearing_date', models.DateField(default=django.utils.timezone.now)),
                ('deposited_by', models.CharField(blank=True, max_length=254, null=True)),
                ('narration', models.TextField(blank=True, null=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheque_deposits', to='ledger.Account')),
                ('benefactor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.Account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
            ],
        ),
        migrations.CreateModel(
            name='ChequeDepositRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheque_number', models.CharField(max_length=50)),
                ('cheque_date', models.DateField(default=django.utils.timezone.now)),
                ('drawee_bank', models.CharField(max_length=254)),
                ('drawee_bank_address', models.CharField(max_length=254)),
                ('amount', models.FloatField()),
                ('cheque_deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='bank.ChequeDeposit')),
            ],
        ),
    ]
