# Generated by Django 4.2.17 on 2025-01-15 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('ledger', '0001_initial'),
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationstatement',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_reconciliation_statements', to='ledger.account'),
        ),
        migrations.AddField(
            model_name='reconciliationstatement',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_reconciliation_statements', to='company.company'),
        ),
        migrations.AddField(
            model_name='reconciliationrowtransaction',
            name='reconciliation_row',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='bank.reconciliationrow'),
        ),
        migrations.AddField(
            model_name='reconciliationrowtransaction',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_rows_transactions', to='ledger.transaction'),
        ),
        migrations.AddField(
            model_name='reconciliationrow',
            name='statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='bank.reconciliationstatement'),
        ),
        migrations.AddField(
            model_name='fundtransfertemplate',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
        migrations.AddField(
            model_name='fundtransfertemplate',
            name='from_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fund_transfers_from_template', to='ledger.account'),
        ),
        migrations.AddField(
            model_name='fundtransfertemplate',
            name='to_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fund_transfers_to_template', to='ledger.account'),
        ),
        migrations.AddField(
            model_name='fundtransfertemplate',
            name='transaction_fee_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='charged_fund_transfers_template', to='ledger.account'),
        ),
        migrations.AddField(
            model_name='fundtransfer',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
        migrations.AddField(
            model_name='fundtransfer',
            name='from_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fund_transfers_from', to='ledger.account'),
        ),
        migrations.AddField(
            model_name='fundtransfer',
            name='to_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fund_transfers_to', to='ledger.account'),
        ),
        migrations.AddField(
            model_name='fundtransfer',
            name='transaction_fee_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='charged_fund_transfers', to='ledger.account'),
        ),
        migrations.AddField(
            model_name='chequeissue',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bank.bankaccount'),
        ),
        migrations.AddField(
            model_name='chequeissue',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
        migrations.AddField(
            model_name='chequeissue',
            name='dr_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheque_issues', to='ledger.account'),
        ),
        migrations.AddField(
            model_name='chequeissue',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.party'),
        ),
        migrations.AddField(
            model_name='chequedeposit',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheque_deposits', to='bank.bankaccount'),
        ),
        migrations.AddField(
            model_name='chequedeposit',
            name='benefactor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.account'),
        ),
        migrations.AddField(
            model_name='chequedeposit',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
        migrations.AddField(
            model_name='bankcashdeposit',
            name='bank_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_cash_deposits', to='bank.bankaccount'),
        ),
        migrations.AddField(
            model_name='bankcashdeposit',
            name='benefactor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.account'),
        ),
        migrations.AddField(
            model_name='bankcashdeposit',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='commission_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_accounts', to='ledger.account'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='company.company'),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='ledger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_accounts', to='ledger.account'),
        ),
    ]
