# Generated by Django 2.1.5 on 2019-08-12 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20190725_1704'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ledger', '0013_auto_20190812_1713'),
        ('bank', '0002_chequedeposit_chequedepositrow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('short_name', models.CharField(max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
            ],
        ),
        migrations.CreateModel(
            name='BankBranch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('start_cheque_no', models.IntegerField(default=0)),
                ('current_cheque_no', models.IntegerField(blank=True, null=True)),
                ('cheque_prefix', models.CharField(blank=True, max_length=10, null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='bank.Bank')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
            ],
            options={
                'verbose_name_plural': 'Bank branches',
            },
        ),
        migrations.CreateModel(
            name='ChequeVoucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheque_no', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField()),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.IntegerField()),
                ('bank_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bank.BankBranch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ledger.Party')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheques', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
