# Generated by Django 4.2.17 on 2025-04-11 07:37

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='transaction_commission_percent',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='bankcashdeposit',
            name='amount',
            field=models.DecimalField(decimal_places=6, max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='chequedeposit',
            name='amount',
            field=models.DecimalField(decimal_places=6, max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='chequeissue',
            name='amount',
            field=models.DecimalField(decimal_places=6, max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='fundtransfer',
            name='amount',
            field=models.DecimalField(decimal_places=6, max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='fundtransfer',
            name='transaction_fee',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='fundtransfertemplate',
            name='transaction_fee',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='reconciliationrow',
            name='adjustment_amount',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='reconciliationrow',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='reconciliationrow',
            name='cr_amount',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='reconciliationrow',
            name='dr_amount',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
    ]
