# Generated by Django 4.2.17 on 2025-04-16 10:21

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_alter_bankaccount_transaction_commission_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='transaction_commission_percent',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
    ]
