# Generated by Django 2.1.5 on 2019-08-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_bank_bankbranch_chequevoucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='short_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
