# Generated by Django 2.1.5 on 2019-09-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_bankaccount_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='current_cheque_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='start_cheque_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
