# Generated by Django 2.1.5 on 2019-09-08 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_auto_20190908_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='chequevoucher',
            name='bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bank.BankAccount'),
        ),
    ]
