# Generated by Django 2.1.5 on 2019-09-08 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0006_chequevoucher_bank_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chequevoucher',
            name='bank_branch',
        ),
    ]
