# Generated by Django 2.1.5 on 2019-09-08 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_remove_chequevoucher_bank_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='company',
        ),
        migrations.RemoveField(
            model_name='bankbranch',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='bankbranch',
            name='company',
        ),
        migrations.DeleteModel(
            name='Bank',
        ),
        migrations.DeleteModel(
            name='BankBranch',
        ),
    ]
