# Generated by Django 2.1.5 on 2019-09-12 12:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ledger', '0022_auto_20190912_1822'),
        ('users', '0042_auto_20190909_1652'),
        ('bank', '0008_auto_20190908_2130'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChequeVoucher',
            new_name='ChequeIssue',
        ),
    ]
