# Generated by Django 2.1.5 on 2019-09-19 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0009_auto_20190912_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chequedeposit',
            name='bank_account',
        ),
    ]
