# Generated by Django 2.1.5 on 2019-09-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0009_auto_20190912_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='chequedeposit',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Issued', 'Issued'), ('Cleared', 'Cleared')], default='Draft', max_length=200),
        ),
        migrations.AlterField(
            model_name='chequedeposit',
            name='voucher_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
