# Generated by Django 2.1.5 on 2019-09-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0010_auto_20190913_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequedeposit',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Issued', 'Issued'), ('Cleared', 'Cleared')], default='Draft', max_length=20),
        ),
    ]
