# Generated by Django 2.1.5 on 2019-09-19 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0010_remove_chequedeposit_bank_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='chequedeposit',
            name='bank_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cheque_deposits', to='bank.BankAccount'),
            preserve_default=False,
        ),
    ]
