# Generated by Django 2.1.5 on 2019-09-19 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0011_chequedeposit_bank_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequedeposit',
            name='voucher_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
