# Generated by Django 2.1.5 on 2019-09-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0011_auto_20190913_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequedeposit',
            name='clearing_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
