# Generated by Django 2.1.5 on 2019-09-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0012_auto_20190913_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequedeposit',
            name='voucher_no',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
