# Generated by Django 2.1.5 on 2019-09-19 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0013_auto_20190913_2019'),
        ('bank', '0012_auto_20190919_2154'),
    ]

    operations = [
    ]
