# Generated by Django 2.1.5 on 2019-09-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0014_merge_20190919_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequedeposit',
            name='voucher_no',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
