# Generated by Django 2.1.6 on 2019-09-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0015_auto_20190921_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequedeposit',
            name='deposited_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chequedepositrow',
            name='drawee_bank',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='chequedepositrow',
            name='drawee_bank_address',
            field=models.CharField(max_length=255),
        ),
    ]
