# Generated by Django 2.1.5 on 2019-09-24 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0016_auto_20190922_2251'),
        ('bank', '0016_auto_20190922_1229'),
    ]

    operations = [
    ]
