# Generated by Django 2.1.6 on 2019-09-29 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0017_merge_20190927_1144'),
        ('bank', '0017_merge_20190924_1531'),
        ('bank', '0017_merge_20190924_1948'),
    ]

    operations = [
    ]
