# Generated by Django 2.1.5 on 2019-10-31 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0018_merge_20190929_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='start_cheque_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
