# Generated by Django 2.1.5 on 2019-10-31 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0019_auto_20191031_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccount',
            old_name='start_cheque_no',
            new_name='next_cheque_no',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='current_cheque_no',
        ),
    ]
