# Generated by Django 2.1.5 on 2019-10-31 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0035_auto_20191013_1324'),
        ('bank', '0020_auto_20191031_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chequeissue',
            name='user',
        ),
        migrations.AddField(
            model_name='chequeissue',
            name='dr_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheque_issues', to='ledger.Account'),
        ),
    ]
