# Generated by Django 2.1.5 on 2019-11-14 13:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0021_auto_20191031_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chequedepositrow',
            name='cheque_deposit',
        ),
        migrations.AddField(
            model_name='chequedeposit',
            name='amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chequedeposit',
            name='cheque_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='chequedeposit',
            name='cheque_number',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chequedeposit',
            name='drawee_bank',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ChequeDepositRow',
        ),
    ]
