# Generated by Django 2.1.5 on 2019-11-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0022_auto_20191114_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequedeposit',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='chequedeposit',
            name='drawee_bank',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
