# Generated by Django 2.1.5 on 2019-11-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0024_auto_20191114_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequedeposit',
            name='cheque_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
