# Generated by Django 2.1.5 on 2019-11-14 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0025_auto_20191114_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequedeposit',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Issued', 'Issued'), ('Cleared', 'Cleared'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20),
        ),
    ]
