# Generated by Django 2.1.5 on 2020-03-01 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0026_auto_20191115_0100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chequeissue',
            old_name='customer_name',
            new_name='issued_to',
        ),
    ]
