# Generated by Django 2.1.5 on 2020-03-01 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0027_auto_20200301_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequeissue',
            name='bank_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='bank.BankAccount'),
            preserve_default=False,
        ),
    ]
