# Generated by Django 2.1.5 on 2020-03-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0028_auto_20200301_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='chequeissue',
            name='status',
            field=models.CharField(choices=[('Issued', 'Issued'), ('Cancelled', 'Cancelled')], default=('Issued', 'Issued'), max_length=25),
        ),
    ]
