# Generated by Django 2.1.5 on 2020-03-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0029_chequeissue_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequeissue',
            name='status',
            field=models.CharField(choices=[('Issued', 'Issued'), ('Cancelled', 'Cancelled')], default='Issued', max_length=25),
        ),
    ]
