# Generated by Django 2.2.6 on 2020-03-17 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0043_auto_20200313_2140'),
        ('users', '0076_auto_20200302_1539'),
        ('bank', '0030_auto_20200313_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankCashDeposit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.IntegerField(blank=True, default=None, null=True)),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('deposited_by', models.CharField(blank=True, max_length=255, null=True)),
                ('narration', models.TextField(blank=True, null=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_cash_deposits', to='bank.BankAccount')),
                ('benefactor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.Account')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
