# Generated by Django 2.1.5 on 2020-09-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0031_bankcashdeposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='is_wallet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='transaction_commission_percent',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_number',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
