# Generated by Django 2.1.5 on 2020-09-17 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0043_auto_20200313_2140'),
        ('bank', '0032_auto_20200918_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='commission_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_accounts', to='ledger.Account'),
        ),
    ]
