# Generated by Django 2.1.5 on 2021-03-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0033_bankaccount_commission_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequeissue',
            name='amount',
            field=models.FloatField(),
        ),
    ]
