# Generated by Django 2.1.5 on 2021-07-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0035_fundtransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundtransfer',
            name='narration',
            field=models.TextField(blank=True, null=True),
        ),
    ]
