# Generated by Django 2.1.5 on 2021-07-20 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0036_fundtransfer_narration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundtransfer',
            name='transaction_fee_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='charged_fund_transfers', to='ledger.Account'),
        ),
    ]
