# Generated by Django 2.1.5 on 2021-07-20 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0045_communicationlog'),
        ('users', '0079_auto_20210720_2138'),
        ('bank', '0037_auto_20210720_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundTransferTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_fee', models.FloatField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
                ('from_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fund_transfers_from_template', to='ledger.Account')),
                ('to_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fund_transfers_to_template', to='ledger.Account')),
                ('transaction_fee_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='charged_fund_transfers_template', to='ledger.Account')),
            ],
        ),
    ]
