# Generated by Django 2.1.5 on 2021-07-20 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0038_fundtransfertemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundtransfertemplate',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
