# Generated by Django 2.1.5 on 2021-08-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0039_fundtransfertemplate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankcashdeposit',
            name='status',
            field=models.CharField(choices=[('Cleared', 'Cleared'), ('Cancelled', 'Cancelled')], default='Cleared', max_length=25),
        ),
    ]
