# Generated by Django 4.1.1 on 2023-11-02 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0040_bankcashdeposit_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequedeposit',
            name='voucher_no',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
