# Generated by Django 4.1.1 on 2023-11-23 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0041_alter_chequedeposit_voucher_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'ordering': ['-id']},
        ),
    ]
