# Generated by Django 2.1.5 on 2019-02-08 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_auto_20190208_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxScheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('rate', models.FloatField()),
                ('recoverable', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_schemes', to='company.Company')),
            ],
        ),
    ]
