# Generated by Django 2.1.5 on 2019-02-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxscheme',
            name='short_name',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
