# Generated by Django 2.1.5 on 2019-02-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0002_taxscheme_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxscheme',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
