# Generated by Django 4.2.20 on 2025-05-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0002_alter_taxpayment_amount_alter_taxscheme_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxscheme',
            name='short_name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
