# Generated by Django 2.1.5 on 2019-03-03 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0005_auto_20190303_1506'),
        ('tax', '0003_taxscheme_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxscheme',
            name='payable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_payable', to='ledger.Account'),
        ),
        migrations.AddField(
            model_name='taxscheme',
            name='receivable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_receivable', to='ledger.Account'),
        ),
    ]
