# Generated by Django 2.1.5 on 2019-05-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0004_auto_20190303_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxscheme',
            name='short_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
