# Generated by Django 2.1.5 on 2019-09-13 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_auto_20190913_1914'),
        ('tax', '0005_auto_20190522_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_payments', to='company.Company')),
                ('tax_scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tax.TaxScheme')),
            ],
        ),
    ]
