# Generated by Django 2.1.5 on 2019-09-13 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0023_auto_20190913_1914'),
        ('tax', '0006_taxpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxpayment',
            name='cr_account',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tax_payments', to='ledger.Account'),
            preserve_default=False,
        ),
    ]
