# Generated by Django 2.1.5 on 2019-09-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0007_taxpayment_cr_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxpayment',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Paid', 'Paid'), ('Cancelled', 'Cancelled')], default='Draft', max_length=10),
        ),
    ]
