# Generated by Django 2.1.5 on 2019-09-22 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_auto_20190921_1617'),
        ('tax', '0008_taxpayment_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taxscheme',
            unique_together={('short_name', 'company')},
        ),
    ]
