# Generated by Django 2.1.5 on 2019-10-13 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0009_auto_20190922_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxscheme',
            name='payable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payable_taxes', to='ledger.Account'),
        ),
        migrations.AlterField(
            model_name='taxscheme',
            name='receivable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receivable_taxes', to='ledger.Account'),
        ),
    ]
