# Generated by Django 4.1.1 on 2023-11-23 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0010_auto_20191013_1324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxscheme',
            options={'ordering': ['-id']},
        ),
    ]
