# Generated by Django 4.2.16 on 2024-12-03 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('tax', '0011_alter_taxscheme_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxpayment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_payments', to='company.company'),
        ),
        migrations.AlterField(
            model_name='taxscheme',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_schemes', to='company.company'),
        ),
    ]
