# Generated by Django 2.1.5 on 2019-02-08 11:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('full_name', models.CharField(max_length=245)),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('address', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('contact_no', models.CharField(blank=True, max_length=25, null=True)),
                ('organization_type', models.CharField(choices=[('sole_proprietorship', 'Sole Proprietorship'), ('partnership', 'Partnership'), ('corporation', 'Corporation'), ('non_profit', 'Non-profit')], default='sole_proprietorship', max_length=254)),
                ('tax_registration_number', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
