# Generated by Django 4.2.19 on 2025-02-24 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_email_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_password_autoset',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_password_expired',
        ),
    ]
