# Generated by Django 4.2.17 on 2025-02-24 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_is_email_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login_ip',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login_medium',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login_uagent',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_logout_ip',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_logout_time',
        ),
    ]
