# Generated by Django 2.1.5 on 2019-03-11 06:09

from django.db import migrations, models
import django.db.models.deletion
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190208_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('modules', models.CharField(blank=True, choices=[('Dashboard', 'Dashboard'), ('ItemView', 'ItemView'), ('ItemCreate', 'ItemCreate'), ('ItemModify', 'ItemModify'), ('ItemDelete', 'ItemDelete')], max_length=1000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.Role'),
        ),
    ]
