# Generated by Django 2.1.5 on 2019-03-11 07:06

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190311_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='modules',
            field=models.CharField(blank=True, choices=[('Dashboard', 'Dashboard'), ('ItemView', 'ItemView'), ('ItemCreate', 'ItemCreate'), ('ItemModify', 'ItemModify'), ('ItemDelete', 'ItemDelete'), ('PartyView', 'PartyView'), ('PartyCreate', 'PartyCreate'), ('PartyModify', 'PartyModify'), ('PartyDelete', 'PartyDelete')], max_length=1000, null=True),
        ),
    ]
