# Generated by Django 2.1.5 on 2019-03-11 07:19

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190311_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='modules',
            field=models.CharField(blank=True, choices=[('Dashboard', 'Dashboard'), ('ItemView', 'ItemView'), ('ItemCreate', 'ItemCreate'), ('ItemModify', 'ItemModify'), ('ItemDelete', 'ItemDelete'), ('PartyView', 'PartyView'), ('PartyCreate', 'PartyCreate'), ('PartyModify', 'PartyModify'), ('PartyDelete', 'PartyDelete'), ('LedgerView', 'LedgerView'), ('LedgerCreate', 'LedgerCreate'), ('LedgerModify', 'LedgerModify'), ('LedgerDelete', 'LedgerDelete'), ('TaxSchemeView', 'TaxSchemeView'), ('TaxSchemeCreate', 'TaxSchemeCreate'), ('TaxSchemeModify', 'TaxSchemeModify'), ('TaxSchemeDelete', 'TaxSchemeDelete'), ('SaleVoucherView', 'SaleVoucherView'), ('SaleVoucherCreate', 'SaleVoucherCreate'), ('SaleVoucherModify', 'SaleVoucherModify'), ('SaleVoucherDelete', 'SaleVoucherDelete')], max_length=1000, null=True),
        ),
    ]
