# Generated by Django 2.1.5 on 2019-05-19 09:21

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20190318_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='modules',
            field=models.CharField(blank=True, choices=[('Dashboard', 'Dashboard'), ('ItemView', 'ItemView'), ('ItemCreate', 'ItemCreate'), ('ItemModify', 'ItemModify'), ('ItemDelete', 'ItemDelete'), ('PartyView', 'PartyView'), ('PartyCreate', 'PartyCreate'), ('PartyModify', 'PartyModify'), ('PartyDelete', 'PartyDelete'), ('AccountView', 'AccountView'), ('AccountCreate', 'AccountCreate'), ('AccountModify', 'AccountModify'), ('AccountDelete', 'AccountDelete'), ('TaxSchemeView', 'TaxSchemeView'), ('TaxSchemeCreate', 'TaxSchemeCreate'), ('TaxSchemeModify', 'TaxSchemeModify'), ('TaxSchemeDelete', 'TaxSchemeDelete'), ('SalesVoucherView', 'SalesVoucherView'), ('SalesVoucherCreate', 'SalesVoucherCreate'), ('SalesVoucherModify', 'SalesVoucherModify'), ('SalesVoucherDelete', 'SalesVoucherDelete'), ('CreditVoucherView', 'CreditVoucherView'), ('CreditVoucherCreate', 'CreditVoucherCreate'), ('CreditVoucherModify', 'CreditVoucherModify'), ('CreditVoucherDelete', 'CreditVoucherDelete'), ('ChequeVoucherView', 'ChequeVoucherView'), ('ChequeVoucherCreate', 'ChequeVoucherCreate'), ('ChequeVoucherModify', 'ChequeVoucherModify'), ('ChequeVoucherDelete', 'ChequeVoucherDelete'), ('BankAccountView', 'BankAccountView'), ('BankAccountCreate', 'BankAccountCreate'), ('BankAccountModify', 'BankAccountModify'), ('BankAccountDelete', 'BankAccountDelete'), ('InvoiceDesignView', 'InvoiceDesignView'), ('InvoiceDesignCreate', 'InvoiceDesignCreate'), ('InvoiceDesignModify', 'InvoiceDesignModify'), ('CategoryView', 'CategoryView'), ('CategoryCreate', 'CategoryCreate'), ('CategoryModify', 'CategoryModify')], max_length=1000, null=True),
        ),
    ]
