# Generated by Django 2.1.5 on 2019-05-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20190521_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='force_preview_before_save',
            field=models.BooleanField(default=False),
        ),
    ]
