# Generated by Django 2.1.5 on 2019-07-25 11:19

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20190611_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='modules',
            field=models.CharField(blank=True, choices=[('Dashboard', 'Dashboard'), ('ItemView', 'ItemView'), ('ItemCreate', 'ItemCreate'), ('ItemModify', 'ItemModify'), ('ItemDelete', 'ItemDelete'), ('UnitView', 'UnitView'), ('UnitCreate', 'UnitCreate'), ('UnitModify', 'UnitModify'), ('UnitDelete', 'UnitDelete'), ('PartyView', 'PartyView'), ('PartyCreate', 'PartyCreate'), ('PartyModify', 'PartyModify'), ('PartyDelete', 'PartyDelete'), ('AccountView', 'AccountView'), ('AccountCreate', 'AccountCreate'), ('AccountModify', 'AccountModify'), ('AccountDelete', 'AccountDelete'), ('TaxSchemeView', 'TaxSchemeView'), ('TaxSchemeCreate', 'TaxSchemeCreate'), ('TaxSchemeModify', 'TaxSchemeModify'), ('TaxSchemeDelete', 'TaxSchemeDelete'), ('SalesVoucherView', 'SalesVoucherView'), ('SalesVoucherCreate', 'SalesVoucherCreate'), ('SalesVoucherModify', 'SalesVoucherModify'), ('SalesVoucherIssuedModify', 'SalesVoucherIssuedModify'), ('SalesVoucherDelete', 'SalesVoucherDelete'), ('PurchaseVoucherView', 'PurchaseVoucherView'), ('PurchaseVoucherCreate', 'PurchaseVoucherCreate'), ('PurchaseVoucherModify', 'PurchaseVoucherModify'), ('PurchaseVoucherDelete', 'PurchaseVoucherDelete'), ('CreditVoucherView', 'CreditVoucherView'), ('CreditVoucherCreate', 'CreditVoucherCreate'), ('CreditVoucherModify', 'CreditVoucherModify'), ('CreditVoucherDelete', 'CreditVoucherDelete'), ('ChequeVoucherView', 'ChequeVoucherView'), ('ChequeVoucherCreate', 'ChequeVoucherCreate'), ('ChequeVoucherModify', 'ChequeVoucherModify'), ('ChequeVoucherDelete', 'ChequeVoucherDelete'), ('ChequeDepositView', 'ChequeDepositView'), ('ChequeDepositCreate', 'ChequeDepositCreate'), ('ChequeDepositModify', 'ChequeDepositModify'), ('ChequeDepositDelete', 'ChequeDepositDelete'), ('BankAccountView', 'BankAccountView'), ('BankAccountCreate', 'BankAccountCreate'), ('BankAccountModify', 'BankAccountModify'), ('BankAccountDelete', 'BankAccountDelete'), ('InvoiceDesignView', 'InvoiceDesignView'), ('InvoiceDesignCreate', 'InvoiceDesignCreate'), ('InvoiceDesignModify', 'InvoiceDesignModify'), ('CategoryView', 'CategoryView'), ('CategoryCreate', 'CategoryCreate'), ('CategoryModify', 'CategoryModify'), ('JournalVoucherView', 'JournalVoucherView'), ('JournalVoucherCreate', 'JournalVoucherCreate'), ('JournalVoucherModify', 'JournalVoucherModify'), ('BankBranchView', 'BankBranchView'), ('BankBranchCreate', 'BankBranchCreate'), ('BankBranchModify', 'BankBranchModify'), ('BankBranchDelete', 'BankBranchDelete')], max_length=1000, null=True),
        ),
    ]
