# Generated by Django 2.1.5 on 2019-09-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20190830_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='enable_sales_voucher_update',
            field=models.BooleanField(default=False),
        ),
    ]
