# Generated by Django 2.1.5 on 2019-09-03 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_fiscalyear'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiscalyear',
            name='company',
        ),
        migrations.AddField(
            model_name='company',
            name='current_fiscal_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='company.FiscalYear'),
            preserve_default=False,
        ),
    ]
