# Generated by Django 2.1.5 on 2019-09-03 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_auto_20190903_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='current_fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.FiscalYear'),
        ),
    ]
