# Generated by Django 2.1.5 on 2019-09-03 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_auto_20190903_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='current_fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='company.FiscalYear'),
        ),
    ]
