# Generated by Django 2.1.5 on 2019-09-06 14:07

from django.db import migrations, models
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_auto_20190906_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='enable_credit_note_update',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='modules',
            field=models.CharField(blank=True, choices=[('Dashboard', 'Dashboard'), ('ItemView', 'ItemView'), ('ItemCreate', 'ItemCreate'), ('ItemModify', 'ItemModify'), ('ItemDelete', 'ItemDelete'), ('UnitView', 'UnitView'), ('UnitCreate', 'UnitCreate'), ('UnitModify', 'UnitModify'), ('UnitDelete', 'UnitDelete'), ('PartyView', 'PartyView'), ('PartyCreate', 'PartyCreate'), ('PartyModify', 'PartyModify'), ('PartyDelete', 'PartyDelete'), ('AccountView', 'AccountView'), ('AccountCreate', 'AccountCreate'), ('AccountModify', 'AccountModify'), ('AccountDelete', 'AccountDelete'), ('TaxSchemeView', 'TaxSchemeView'), ('TaxSchemeCreate', 'TaxSchemeCreate'), ('TaxSchemeModify', 'TaxSchemeModify'), ('TaxSchemeDelete', 'TaxSchemeDelete'), ('SalesVoucherView', 'SalesVoucherView'), ('SalesVoucherCreate', 'SalesVoucherCreate'), ('SalesVoucherModify', 'SalesVoucherModify'), ('SalesVoucherIssuedModify', 'SalesVoucherIssuedModify'), ('SalesVoucherDelete', 'SalesVoucherDelete'), ('PurchaseVoucherView', 'PurchaseVoucherView'), ('PurchaseVoucherCreate', 'PurchaseVoucherCreate'), ('PurchaseVoucherModify', 'PurchaseVoucherModify'), ('PurchaseVoucherDelete', 'PurchaseVoucherDelete'), ('CreditNoteView', 'CreditNoteView'), ('CreditNoteCreate', 'CreditNoteCreate'), ('CreditNoteModify', 'CreditNoteModify'), ('CreditNoteDelete', 'CreditNoteDelete'), ('CreditNoteIssuedModify', 'CreditNoteIssuedModify'), ('ChequeVoucherView', 'ChequeVoucherView'), ('ChequeVoucherCreate', 'ChequeVoucherCreate'), ('ChequeVoucherModify', 'ChequeVoucherModify'), ('ChequeVoucherDelete', 'ChequeVoucherDelete'), ('ChequeDepositView', 'ChequeDepositView'), ('ChequeDepositCreate', 'ChequeDepositCreate'), ('ChequeDepositModify', 'ChequeDepositModify'), ('ChequeDepositDelete', 'ChequeDepositDelete'), ('BankAccountView', 'BankAccountView'), ('BankAccountCreate', 'BankAccountCreate'), ('BankAccountModify', 'BankAccountModify'), ('BankAccountDelete', 'BankAccountDelete'), ('InvoiceDesignView', 'InvoiceDesignView'), ('InvoiceDesignCreate', 'InvoiceDesignCreate'), ('InvoiceDesignModify', 'InvoiceDesignModify'), ('CategoryView', 'CategoryView'), ('CategoryCreate', 'CategoryCreate'), ('CategoryModify', 'CategoryModify'), ('JournalVoucherView', 'JournalVoucherView'), ('JournalVoucherCreate', 'JournalVoucherCreate'), ('JournalVoucherModify', 'JournalVoucherModify'), ('BankBranchView', 'BankBranchView'), ('BankBranchCreate', 'BankBranchCreate'), ('BankBranchModify', 'BankBranchModify'), ('BankBranchDelete', 'BankBranchDelete'), ('InventoryCategoryView', 'InventoryCategoryView'), ('InventoryCategoryCreate', 'InventoryCategoryCreate'), ('InventoryCategoryModify', 'InventoryCategoryModify'), ('InventoryCategoryDelete', 'InventoryCategoryDelete'), ('BrandView', 'BrandView'), ('BrandCreate', 'BrandCreate'), ('BrandModify', 'BrandModify'), ('BrandDelete', 'BrandDelete'), ('SalesDiscountView', 'SalesDiscountView'), ('SalesDiscountCreate', 'SalesDiscountCreate'), ('SalesDiscountModify', 'SalesDiscountModify'), ('SalesDiscountDelete', 'SalesDiscountDelete'), ('PurchaseDiscountView', 'PurchaseDiscountView'), ('PurchaseDiscountCreate', 'PurchaseDiscountCreate'), ('PurchaseDiscountModify', 'PurchaseDiscountModify'), ('PurchaseDiscountDelete', 'PurchaseDiscountDelete'), ('InventoryAccountView', 'InventoryAccountView'), ('InventoryAccountCreate', 'InventoryAccountCreate'), ('InventoryAccountModify', 'InventoryAccountModify'), ('InventoryAccountDelete', 'InventoryAccountDelete'), ('BookView', 'BookView'), ('BookCreate', 'BookCreate'), ('BookModify', 'BookModify'), ('LogEntryView', 'LogEntryView')], max_length=2000, null=True),
        ),
    ]
