# Generated by Django 2.1.6 on 2019-09-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_auto_20190908_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='enable_debit_note_update',
            field=models.BooleanField(default=False),
        ),
    ]
