# Generated by Django 2.1.5 on 2019-09-09 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_company_enable_debit_note_update'),
        ('users', '0040_auto_20190909_1413'),
    ]

    operations = [
    ]
