# Generated by Django 2.1.5 on 2019-09-09 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_merge_20190909_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='enable_sales_voucher_update',
            new_name='enable_sales_invoice_update',
        ),
    ]
