# Generated by Django 2.1.5 on 2019-09-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_auto_20190909_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='enable_sales_agents',
            field=models.BooleanField(default=False),
        ),
    ]
