# Generated by Django 2.1.5 on 2019-09-13 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_auto_20190912_1825'),
        ('users', '0043_company_enable_sales_agents'),
    ]

    operations = [
    ]
