# Generated by Django 2.1.5 on 2019-09-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_auto_20190913_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='enable_cheque_deposit_update',
            field=models.BooleanField(default=False),
        ),
    ]
