# Generated by Django 2.1.5 on 2019-09-15 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_auto_20190913_2344'),
        ('users', '0047_company_enable_cheque_deposit_update'),
    ]

    operations = [
    ]
