# Generated by Django 2.1.5 on 2019-09-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_auto_20190916_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='organization_type',
            field=models.CharField(choices=[('private_limited', 'Private Limited'), ('public_limited', 'Public Limited'), ('sole_proprietorship', 'Sole Proprietorship'), ('partnership', 'Partnership'), ('corporation', 'Corporation'), ('non_profit', 'Non-profit')], default='sole_proprietorship', max_length=255),
        ),
    ]
