# Generated by Django 2.1.5 on 2019-09-19 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_auto_20190916_1308'),
        ('users', '0048_merge_20190915_1730'),
    ]

    operations = [
    ]
