# Generated by Django 2.1.5 on 2019-09-21 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_auto_20190918_2214'),
        ('users', '0049_merge_20190919_2230'),
    ]

    operations = [
    ]
