# Generated by Django 2.1.5 on 2019-10-01 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_auto_20191001_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='organization_type',
            field=models.CharField(choices=[('private_limited', 'Private Limited'), ('public_limited', 'Public Limited'), ('sole_proprietorship', 'Sole Proprietorship'), ('partnership', 'Partnership'), ('corporation', 'Corporation'), ('non_profit', 'Non-profit')], default='private_limited', max_length=255),
        ),
    ]
