# Generated by Django 2.1.5 on 2019-10-12 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_auto_20191012_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='force_preview_before_save',
        ),
    ]
