# Generated by Django 2.1.5 on 2019-10-31 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0060_auto_20191027_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='synchronize_cbms_nepal_live',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='synchronize_cbms_nepal_test',
            field=models.BooleanField(default=False),
        ),
    ]
