# Generated by Django 2.1.5 on 2019-11-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0061_auto_20191031_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='tax_registration_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
