# Generated by Django 2.1.5 on 2019-11-07 20:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0063_accesskey'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesskey',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accesskey',
            name='key',
            field=models.UUIDField(default=uuid.UUID('d8fda98f-ca2b-49e6-a336-9f888937de18')),
        ),
    ]
