# Generated by Django 2.1.5 on 2019-11-07 20:29

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0064_auto_20191108_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesskey',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='accesskey',
            name='key',
            field=models.UUIDField(default=uuid.UUID('f8e20d0e-e28d-4306-a325-b05de1197a24')),
        ),
    ]
