# Generated by Django 2.1.6 on 2019-11-08 05:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0065_auto_20191108_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesskey',
            name='key',
            field=models.UUIDField(default=uuid.UUID('9713c897-05d8-41ed-a60e-14d34b8f5cd2')),
        ),
    ]
