# Generated by Django 2.1.5 on 2019-11-11 23:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0066_auto_20191108_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesskey',
            name='key',
            field=models.UUIDField(default=uuid.UUID('badccbde-51eb-4b65-a316-4f5268eed0c1')),
        ),
    ]
