# Generated by Django 2.1.5 on 2019-11-12 01:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0067_auto_20191112_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesskey',
            name='key',
            field=models.UUIDField(default=uuid.UUID('e69e0b9c-48c6-4151-81b1-281aae222df8')),
        ),
    ]
