# Generated by Django 2.1.5 on 2019-11-12 01:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0068_auto_20191112_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesskey',
            name='key',
            field=models.UUIDField(default=uuid.UUID('446476d6-663e-4f02-b67b-1990b4fd666b')),
        ),
    ]
