# Generated by Django 2.1.5 on 2019-11-14 17:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0069_auto_20191112_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesskey',
            name='key',
            field=models.UUIDField(default=uuid.UUID('32500d5e-a748-457d-a8ab-6ad4ae1d4d1e')),
        ),
    ]
