# Generated by Django 2.1.5 on 2019-11-14 17:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0071_auto_20191114_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesskey',
            name='key',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
