# Generated by Django 4.1.1 on 2022-09-07 05:43

import django.contrib.postgres.fields
from django.db import migrations, models


def clean_roles(apps, schema_editor):
    model = apps.get_model('users', 'Role')
    model.objects.update(modules='{}')


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0079_auto_20210720_2138'),
    ]

    operations = [
        migrations.RunPython(clean_roles),
        migrations.AlterField(
            model_name='role',
            name='modules',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[
                ('AccountCreate', 'AccountCreate'), ('AccountDelete', 'AccountDelete'),
                ('AccountModify', 'AccountModify'), ('AccountOpeningBalanceCreate', 'AccountOpeningBalanceCreate'),
                ('AccountOpeningBalanceDelete', 'AccountOpeningBalanceDelete'),
                ('AccountOpeningBalanceModify', 'AccountOpeningBalanceModify'),
                ('AccountOpeningBalanceView', 'AccountOpeningBalanceView'), ('AccountView', 'AccountView'),
                ('BankAccountCreate', 'BankAccountCreate'), ('BankAccountDelete', 'BankAccountDelete'),
                ('BankAccountModify', 'BankAccountModify'), ('BankAccountView', 'BankAccountView'),
                ('BankBranchCreate', 'BankBranchCreate'), ('BankBranchDelete', 'BankBranchDelete'),
                ('BankBranchModify', 'BankBranchModify'), ('BankBranchView', 'BankBranchView'),
                ('BankCashDepositCreate', 'BankCashDepositCreate'), ('BankCashDepositDelete', 'BankCashDepositDelete'),
                ('BankCashDepositModify', 'BankCashDepositModify'), ('BankCashDepositView', 'BankCashDepositView'),
                ('BookCreate', 'BookCreate'), ('BookDelete', 'BookDelete'), ('BookModify', 'BookModify'),
                ('BookView', 'BookView'), ('BrandCreate', 'BrandCreate'), ('BrandDelete', 'BrandDelete'),
                ('BrandModify', 'BrandModify'), ('BrandView', 'BrandView'), ('CategoryCreate', 'CategoryCreate'),
                ('CategoryDelete', 'CategoryDelete'), ('CategoryModify', 'CategoryModify'),
                ('CategoryView', 'CategoryView'), ('ChallanCreate', 'ChallanCreate'),
                ('ChallanDelete', 'ChallanDelete'), ('ChallanModify', 'ChallanModify'), ('ChallanView', 'ChallanView'),
                ('ChequeDepositCreate', 'ChequeDepositCreate'), ('ChequeDepositDelete', 'ChequeDepositDelete'),
                ('ChequeDepositModify', 'ChequeDepositModify'), ('ChequeDepositView', 'ChequeDepositView'),
                ('ChequeIssueCreate', 'ChequeIssueCreate'), ('ChequeIssueDelete', 'ChequeIssueDelete'),
                ('ChequeIssueModify', 'ChequeIssueModify'), ('ChequeIssueView', 'ChequeIssueView'),
                ('CreditNoteCancel', 'CreditNoteCancel'), ('CreditNoteCreate', 'CreditNoteCreate'),
                ('CreditNoteDelete', 'CreditNoteDelete'), ('CreditNoteIssuedModify', 'CreditNoteIssuedModify'),
                ('CreditNoteModify', 'CreditNoteModify'), ('CreditNoteView', 'CreditNoteView'),
                ('Dashboard', 'Dashboard'), ('DebitNoteCancel', 'DebitNoteCancel'),
                ('DebitNoteCreate', 'DebitNoteCreate'), ('DebitNoteDelete', 'DebitNoteDelete'),
                ('DebitNoteIssuedModify', 'DebitNoteIssuedModify'), ('DebitNoteModify', 'DebitNoteModify'),
                ('DebitNoteView', 'DebitNoteView'), ('FundTransferCreate', 'FundTransferCreate'),
                ('FundTransferDelete', 'FundTransferDelete'), ('FundTransferModify', 'FundTransferModify'),
                ('FundTransferView', 'FundTransferView'), ('InventoryAccountCreate', 'InventoryAccountCreate'),
                ('InventoryAccountDelete', 'InventoryAccountDelete'),
                ('InventoryAccountModify', 'InventoryAccountModify'), ('InventoryAccountView', 'InventoryAccountView'),
                ('InventoryCategoryCreate', 'InventoryCategoryCreate'),
                ('InventoryCategoryDelete', 'InventoryCategoryDelete'),
                ('InventoryCategoryModify', 'InventoryCategoryModify'),
                ('InventoryCategoryView', 'InventoryCategoryView'), ('InvoiceDesignCreate', 'InvoiceDesignCreate'),
                ('InvoiceDesignDelete', 'InvoiceDesignDelete'), ('InvoiceDesignModify', 'InvoiceDesignModify'),
                ('InvoiceDesignView', 'InvoiceDesignView'), ('ItemCreate', 'ItemCreate'), ('ItemDelete', 'ItemDelete'),
                ('ItemModify', 'ItemModify'), ('ItemView', 'ItemView'),
                ('JournalVoucherCreate', 'JournalVoucherCreate'), ('JournalVoucherDelete', 'JournalVoucherDelete'),
                ('JournalVoucherModify', 'JournalVoucherModify'), ('JournalVoucherView', 'JournalVoucherView'),
                ('LogEntryView', 'LogEntryView'), ('PartyCreate', 'PartyCreate'), ('PartyDelete', 'PartyDelete'),
                ('PartyModify', 'PartyModify'), ('PartyView', 'PartyView'),
                ('PaymentReceiptCreate', 'PaymentReceiptCreate'), ('PaymentReceiptDelete', 'PaymentReceiptDelete'),
                ('PaymentReceiptModify', 'PaymentReceiptModify'), ('PaymentReceiptView', 'PaymentReceiptView'),
                ('PurchaseDiscountCreate', 'PurchaseDiscountCreate'),
                ('PurchaseDiscountDelete', 'PurchaseDiscountDelete'),
                ('PurchaseDiscountModify', 'PurchaseDiscountModify'), ('PurchaseDiscountView', 'PurchaseDiscountView'),
                ('PurchaseSettingCreate', 'PurchaseSettingCreate'), ('PurchaseSettingDelete', 'PurchaseSettingDelete'),
                ('PurchaseSettingModify', 'PurchaseSettingModify'), ('PurchaseSettingView', 'PurchaseSettingView'),
                ('PurchaseVoucherCreate', 'PurchaseVoucherCreate'), ('PurchaseVoucherDelete', 'PurchaseVoucherDelete'),
                ('PurchaseVoucherModify', 'PurchaseVoucherModify'), ('PurchaseVoucherView', 'PurchaseVoucherView'),
                ('SalesAgentCreate', 'SalesAgentCreate'), ('SalesAgentDelete', 'SalesAgentDelete'),
                ('SalesAgentModify', 'SalesAgentModify'), ('SalesAgentView', 'SalesAgentView'),
                ('SalesCancel', 'SalesCancel'), ('SalesCreate', 'SalesCreate'), ('SalesDelete', 'SalesDelete'),
                ('SalesDiscountCreate', 'SalesDiscountCreate'), ('SalesDiscountDelete', 'SalesDiscountDelete'),
                ('SalesDiscountModify', 'SalesDiscountModify'), ('SalesDiscountView', 'SalesDiscountView'),
                ('SalesIssuedModify', 'SalesIssuedModify'), ('SalesModify', 'SalesModify'),
                ('SalesSettingCreate', 'SalesSettingCreate'), ('SalesSettingDelete', 'SalesSettingDelete'),
                ('SalesSettingModify', 'SalesSettingModify'), ('SalesSettingView', 'SalesSettingView'),
                ('SalesView', 'SalesView'), ('TaxPaymentCreate', 'TaxPaymentCreate'),
                ('TaxPaymentDelete', 'TaxPaymentDelete'), ('TaxPaymentModify', 'TaxPaymentModify'),
                ('TaxPaymentView', 'TaxPaymentView'), ('TaxSchemeCreate', 'TaxSchemeCreate'),
                ('TaxSchemeDelete', 'TaxSchemeDelete'), ('TaxSchemeModify', 'TaxSchemeModify'),
                ('TaxSchemeView', 'TaxSchemeView'), ('TransactionChargeCreate', 'TransactionChargeCreate'),
                ('TransactionChargeDelete', 'TransactionChargeDelete'),
                ('TransactionChargeModify', 'TransactionChargeModify'),
                ('TransactionChargeView', 'TransactionChargeView'), ('UnitCreate', 'UnitCreate'),
                ('UnitDelete', 'UnitDelete'), ('UnitModify', 'UnitModify'), ('UnitView', 'UnitView'),
                ('WidgetCreate', 'WidgetCreate'), ('WidgetDelete', 'WidgetDelete'), ('WidgetModify', 'WidgetModify'),
                ('WidgetView', 'WidgetView')], max_length=32), blank=True, default=list, size=None),
        ),
    ]
