# Generated by Django 4.1.1 on 2022-09-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0081_alter_role_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='config_template',
            field=models.CharField(default='np', max_length=255),
        ),
    ]
