# Generated by Django 4.1.1 on 2023-09-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0086_alter_role_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='invoice_template',
            field=models.IntegerField(choices=[(1, 'Template 1'), (2, 'Template 2')], default=1, max_length=255),
        ),
    ]
