# Generated by Django 4.2.2 on 2023-10-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0087_company_invoice_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='invoice_template',
            field=models.IntegerField(choices=[(1, 'Template 1'), (2, 'Template 2')], default=1),
        ),
    ]
