# Generated by Django 4.1.1 on 2024-09-26 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0093_alter_role_modules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='invoice_template',
            field=models.IntegerField(choices=[(1, 'Template 1'), (2, 'Template 2'), (3, 'Template 3')], default=1),
        ),
    ]
