# Generated by Django 4.2.16 on 2024-12-03 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0095_alter_role_modules'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AlterModelTable(
                    name='Company',
                    table='company_company',
                ),
            ],
            state_operations=[
                migrations.DeleteModel(
                    name='Company',
                ),
            ]
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AlterModelTable(
                    name='FiscalYear',
                    table='company_fiscalyear',
                ),
            ],
            state_operations=[
                migrations.DeleteModel(
                    name='FiscalYear',
                ),
            ]
        ),
    ]
