# Generated by Django 4.2.16 on 2024-12-03 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0097_alter_user_company'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.AlterModelTable(
                    name='AccessKey',
                    table='api_accesskey',
                ),
            ],
            state_operations=[
                migrations.DeleteModel(
                    name='AccessKey',
                ),
            ]
        ),
    ]
