# Generated by Django 4.2.17 on 2025-01-15 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('ledger', '0001_initial'),
        ('product', '0001_initial'),
        ('tax', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tax_scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='tax.taxscheme'),
        ),
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.unit'),
        ),
        migrations.AddField(
            model_name='inventorysetting',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_setting', to='company.company'),
        ),
        migrations.AddField(
            model_name='inventoryconversionvoucherrow',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_%(class)s', to='company.company'),
        ),
        migrations.AddField(
            model_name='inventoryconversionvoucherrow',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_conversion_voucher_rows', to='product.item'),
        ),
        migrations.AddField(
            model_name='inventoryconversionvoucherrow',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.unit'),
        ),
        migrations.AddField(
            model_name='inventoryconversionvoucherrow',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='product.inventoryconversionvoucher'),
        ),
        migrations.AddField(
            model_name='inventoryconversionvoucher',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_conversion_voucher', to='company.company'),
        ),
        migrations.AddField(
            model_name='inventoryconversionvoucher',
            name='finished_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_conversion_voucher', to='product.billofmaterial'),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentvoucherrow',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_%(class)s', to='company.company'),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentvoucherrow',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_adjustment_rows', to='product.item'),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentvoucherrow',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.unit'),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentvoucherrow',
            name='voucher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='product.inventoryadjustmentvoucher'),
        ),
        migrations.AddField(
            model_name='inventoryadjustmentvoucher',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_adjustment_voucher', to='company.company'),
        ),
        migrations.AddField(
            model_name='inventoryaccount',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='company.company'),
        ),
        migrations.AddField(
            model_name='category',
            name='account_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_categories', to='ledger.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
        migrations.AddField(
            model_name='category',
            name='dedicated_discount_allowed_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_allowed_categories_dedicated', to='ledger.account'),
        ),
        migrations.AddField(
            model_name='category',
            name='dedicated_discount_received_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_received_categories_dedicated', to='ledger.account'),
        ),
        migrations.AddField(
            model_name='category',
            name='dedicated_purchase_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_categories_dedicated', to='ledger.account'),
        ),
        migrations.AddField(
            model_name='category',
            name='dedicated_sales_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_categories_dedicated', to='ledger.account'),
        ),
        migrations.AddField(
            model_name='category',
            name='default_tax_scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='tax.taxscheme'),
        ),
        migrations.AddField(
            model_name='category',
            name='default_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.unit'),
        ),
        migrations.AddField(
            model_name='category',
            name='direct_expense_account_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_expense_account_category', to='ledger.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='discount_allowed_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_allowed_categories', to='ledger.account'),
        ),
        migrations.AddField(
            model_name='category',
            name='discount_allowed_account_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_allowed_item_categories', to='ledger.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='discount_received_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_received_categories', to='ledger.account'),
        ),
        migrations.AddField(
            model_name='category',
            name='discount_received_account_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_received_item_categories', to='ledger.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='fixed_asset_account_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_asset_account_category', to='ledger.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='indirect_expense_account_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indirect_expense_account_category', to='ledger.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='purchase_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_categories', to='ledger.account'),
        ),
        migrations.AddField(
            model_name='category',
            name='purchase_account_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_item_categories', to='ledger.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='sales_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_categories', to='ledger.account'),
        ),
        migrations.AddField(
            model_name='category',
            name='sales_account_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_item_categories', to='ledger.category'),
        ),
        migrations.AddField(
            model_name='brand',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='company.company'),
        ),
        migrations.AddField(
            model_name='billofmaterialrow',
            name='bill_of_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='product.billofmaterial'),
        ),
        migrations.AddField(
            model_name='billofmaterialrow',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_%(class)s', to='company.company'),
        ),
        migrations.AddField(
            model_name='billofmaterialrow',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.item'),
        ),
        migrations.AddField(
            model_name='billofmaterialrow',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.unit'),
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_of_material', to='company.company'),
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='finished_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_of_material', to='product.item'),
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.unit'),
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('short_name', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('code', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('code', 'company'), ('name', 'company')},
        ),
    ]
