# Generated by Django 4.2.17 on 2025-01-16 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billofmaterialrow',
            name='company',
        ),
        migrations.RemoveField(
            model_name='inventoryadjustmentvoucherrow',
            name='company',
        ),
        migrations.RemoveField(
            model_name='inventoryconversionvoucherrow',
            name='company',
        ),
    ]
