# Generated by Django 2.1.5 on 2019-03-03 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_auto_20190303_1240'),
        ('product', '0002_auto_20190208_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ledger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='ledger.Account'),
        ),
    ]
