# Generated by Django 4.2.17 on 2025-04-11 07:37

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_billofmaterialrow_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billofmaterial',
            name='quantity',
            field=models.DecimalField(decimal_places=6, max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='billofmaterial',
            name='rate',
            field=models.DecimalField(decimal_places=6, max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='billofmaterialrow',
            name='quantity',
            field=models.DecimalField(decimal_places=6, max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='inventoryaccount',
            name='current_balance',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='inventoryaccount',
            name='opening_balance',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000000'), max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='inventoryaccount',
            name='opening_balance_rate',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='inventoryadjustmentvoucher',
            name='meta_discount',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='inventoryadjustmentvoucher',
            name='meta_non_taxable',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='inventoryadjustmentvoucher',
            name='meta_sub_total',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='inventoryadjustmentvoucher',
            name='meta_sub_total_after_row_discounts',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='inventoryadjustmentvoucher',
            name='meta_tax',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='inventoryadjustmentvoucher',
            name='meta_taxable',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='inventoryadjustmentvoucher',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='inventoryadjustmentvoucherrow',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='inventoryadjustmentvoucherrow',
            name='rate',
            field=models.DecimalField(decimal_places=6, max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='inventoryconversionvoucher',
            name='meta_discount',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='inventoryconversionvoucher',
            name='meta_non_taxable',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='inventoryconversionvoucher',
            name='meta_sub_total',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='inventoryconversionvoucher',
            name='meta_sub_total_after_row_discounts',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='inventoryconversionvoucher',
            name='meta_tax',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='inventoryconversionvoucher',
            name='meta_taxable',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='inventoryconversionvoucherrow',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='item',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='item',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='cr_amount',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='current_balance',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='dr_amount',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fifo_inconsistency_quantity',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=24, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='remaining_quantity',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.000000'))]),
        ),
    ]
