# Generated by Django 2.1.5 on 2019-03-05 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tax', '0004_auto_20190303_1548'),
        ('product', '0003_item_ledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tax_scheme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='tax.TaxScheme'),
        ),
    ]
