# Generated by Django 2.1.5 on 2019-03-14 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0009_partyrepresentative_name'),
        ('product', '0004_item_tax_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discount_ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.Account'),
        ),
    ]
