# Generated by Django 4.2.20 on 2025-04-30 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_billofmaterial_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorysetting',
            name='mandate_category',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventorysetting',
            name='mandate_hs_code',
            field=models.BooleanField(default=False),
        ),
    ]
