# Generated by Django 2.1.5 on 2019-05-22 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0009_partyrepresentative_name'),
        ('product', '0005_item_discount_ledger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='discount_ledger',
        ),
        migrations.AddField(
            model_name='item',
            name='discount_allowed_ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allowed_items', to='ledger.Account'),
        ),
        migrations.AddField(
            model_name='item',
            name='discount_payable_ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payable_items', to='ledger.Account'),
        ),
    ]
