# Generated by Django 4.2.20 on 2025-05-02 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_inventorysetting_mandate_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorysetting',
            name='mandate_category',
        ),
        migrations.RemoveField(
            model_name='inventorysetting',
            name='mandate_hs_code',
        ),
    ]
