# Generated by Django 4.2.20 on 2025-05-13 12:26

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_inventorysetting_mandate_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billofmaterial',
            name='quantity',
            field=models.DecimalField(decimal_places=6, max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))]),
        ),
        migrations.AlterField(
            model_name='billofmaterialrow',
            name='quantity',
            field=models.DecimalField(decimal_places=6, max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))]),
        ),
    ]
