# Generated by Django 4.2.20 on 2025-05-22 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_inventorysetting_mandate_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TransatcionRemovalLog',
            new_name='TransactionRemovalLog',
        ),
    ]
