# Generated by Django 4.2.20 on 2025-06-02 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_billofmaterial_quantity_and_more'),
        ('product', '0007_rename_transatcionremovallog_transactionremovallog'),
    ]

    operations = [
    ]
