# Generated by Django 2.1.5 on 2019-07-25 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20190611_1503'),
        ('product', '0008_item_unit'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('code', 'company')},
        ),
    ]
