# Generated by Django 2.1.5 on 2019-07-26 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20190725_1027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='discount_payable_ledger',
            new_name='discount_received_ledger',
        ),
    ]
