# Generated by Django 2.1.5 on 2019-07-27 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0011_auto_20190727_1932'),
        ('product', '0010_auto_20190726_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='ledger',
        ),
        migrations.AddField(
            model_name='item',
            name='purchase_ledger',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_item', to='ledger.Account'),
        ),
        migrations.AddField(
            model_name='item',
            name='sales_ledger',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_item', to='ledger.Account'),
        ),
        migrations.AlterField(
            model_name='item',
            name='discount_allowed_ledger',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allowed_item', to='ledger.Account'),
        ),
        migrations.AlterField(
            model_name='item',
            name='discount_received_ledger',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_item', to='ledger.Account'),
        ),
    ]
