# Generated by Django 2.1.5 on 2019-08-12 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20190725_1704'),
        ('tax', '0005_auto_20190522_1524'),
        ('ledger', '0013_auto_20190812_1713'),
        ('product', '0011_auto_20190727_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('items_sales_ledger_type', models.CharField(choices=[('Use Global Ledger', 'Use Global Ledger'), ("Use Category's Ledger", "Use Category's Ledger"), ('Use Dedicated Ledger', 'Use Dedicated Ledger')], max_length=100)),
                ('items_purchase_ledger_type', models.CharField(choices=[('Use Global Ledger', 'Use Global Ledger'), ("Use Category's Ledger", "Use Category's Ledger"), ('Use Dedicated Ledger', 'Use Dedicated Ledger')], max_length=100)),
                ('items_discount_allowed_ledger_type', models.CharField(choices=[('Use Global Ledger', 'Use Global Ledger'), ("Use Category's Ledger", "Use Category's Ledger"), ('Use Dedicated Ledger', 'Use Dedicated Ledger')], max_length=100)),
                ('items_discount_received_ledger_type', models.CharField(choices=[('Use Global Ledger', 'Use Global Ledger'), ("Use Category's Ledger", "Use Category's Ledger"), ('Use Dedicated Ledger', 'Use Dedicated Ledger')], max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
                ('default_tax_scheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='tax.TaxScheme')),
                ('default_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Unit')),
                ('discount_allowed_ledger', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_allowed_category', to='ledger.Account')),
                ('discount_received_ledger', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_received_category', to='ledger.Account')),
                ('purchase_ledger', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_category', to='ledger.Account')),
                ('sales_ledger', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_category', to='ledger.Account')),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='discount_allowed_ledger',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_allowed_item', to='ledger.Account'),
        ),
        migrations.AlterField(
            model_name='item',
            name='discount_received_ledger',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_received_item', to='ledger.Account'),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='product.Category'),
        ),
    ]
