# Generated by Django 2.1.5 on 2019-08-12 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20190812_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='discount_allowed_ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_allowed_item', to='ledger.Account'),
        ),
        migrations.AlterField(
            model_name='item',
            name='discount_received_ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_received_item', to='ledger.Account'),
        ),
        migrations.AlterField(
            model_name='item',
            name='purchase_ledger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_item', to='ledger.Account'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sales_ledger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_item', to='ledger.Account'),
        ),
    ]
