# Generated by Django 2.1.5 on 2019-08-12 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20190812_1715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='discount_allowed_ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_allowed_category', to='ledger.Account'),
        ),
        migrations.AlterField(
            model_name='category',
            name='discount_received_ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_received_category', to='ledger.Account'),
        ),
        migrations.AlterField(
            model_name='category',
            name='purchase_ledger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_category', to='ledger.Account'),
        ),
        migrations.AlterField(
            model_name='category',
            name='sales_ledger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_category', to='ledger.Account'),
        ),
    ]
