# Generated by Django 2.1.5 on 2019-08-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20190812_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('Sellable', 'Sellable'), ('Expense', 'Expense'), ('Asset', 'Asset')], default='Sellable', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('Sellable', 'Sellable'), ('Expense', 'Expense'), ('Asset', 'Asset')], default='Sellable', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='items_discount_allowed_ledger_type',
            field=models.CharField(choices=[('global', 'Use Global Ledger'), ('category', "Use Category's Ledger"), ('dedicated', 'Use Dedicated Ledger')], max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='items_discount_received_ledger_type',
            field=models.CharField(choices=[('global', 'Use Global Ledger'), ('category', "Use Category's Ledger"), ('dedicated', 'Use Dedicated Ledger')], max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='items_purchase_ledger_type',
            field=models.CharField(choices=[('global', 'Use Global Ledger'), ('category', "Use Category's Ledger"), ('dedicated', 'Use Dedicated Ledger')], max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='items_sales_ledger_type',
            field=models.CharField(choices=[('global', 'Use Global Ledger'), ('category', "Use Category's Ledger"), ('dedicated', 'Use Dedicated Ledger')], max_length=100),
        ),
    ]
