# Generated by Django 2.1.5 on 2019-08-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_auto_20190812_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='items_discount_allowed_ledger_type',
            field=models.CharField(choices=[('dedicated', 'Use Dedicated Ledger'), ('category', "Use Category's Ledger"), ('global', 'Use Global Ledger')], default='dedicated', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='items_discount_received_ledger_type',
            field=models.CharField(choices=[('dedicated', 'Use Dedicated Ledger'), ('category', "Use Category's Ledger"), ('global', 'Use Global Ledger')], default='dedicated', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='items_purchase_ledger_type',
            field=models.CharField(choices=[('dedicated', 'Use Dedicated Ledger'), ('category', "Use Category's Ledger"), ('global', 'Use Global Ledger')], default='dedicated', max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='items_sales_ledger_type',
            field=models.CharField(choices=[('dedicated', 'Use Dedicated Ledger'), ('category', "Use Category's Ledger"), ('global', 'Use Global Ledger')], default='dedicated', max_length=100),
        ),
    ]
