# Generated by Django 2.1.5 on 2019-08-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_auto_20190812_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('Tangible Sellable', 'Tangible Sellable'), ('Intangible Sellable', 'Intangible Sellable'), ('Expense', 'Expense'), ('Asset', 'Asset')], max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('Tangible Sellable', 'Tangible Sellable'), ('Intangible Sellable', 'Intangible Sellable'), ('Expense', 'Expense'), ('Asset', 'Asset')], max_length=20),
        ),
    ]
