# Generated by Django 2.1.5 on 2019-08-12 16:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_auto_20190812_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='extra_fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='extra_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='search_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
