# Generated by Django 2.1.5 on 2019-08-14 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_auto_20190813_0734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='type',
        ),
        migrations.RemoveField(
            model_name='item',
            name='type',
        ),
        migrations.AddField(
            model_name='category',
            name='can_be_purchased',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='can_be_sold',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='track_inventory',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='can_be_purchased',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='can_be_sold',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='item',
            name='track_inventory',
            field=models.BooleanField(default=True),
        ),
    ]
