# Generated by Django 2.1.5 on 2019-08-14 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_auto_20190814_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='fixed_asset',
            field=models.BooleanField(default=False),
        ),
    ]
