# Generated by Django 2.1.5 on 2019-08-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_item_fixed_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='fixed_asset',
            field=models.BooleanField(default=False),
        ),
    ]
