# Generated by Django 2.1.5 on 2019-08-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_category_fixed_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryaccount',
            name='account_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
