# Generated by Django 2.1.5 on 2019-08-14 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_auto_20190814_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryaccount',
            name='opening_rate',
        ),
        migrations.RemoveField(
            model_name='inventoryaccount',
            name='opening_rate_vattable',
        ),
    ]
