# Generated by Django 2.1.5 on 2019-08-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_auto_20190814_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='back_image',
            field=models.ImageField(blank=True, null=True, upload_to='item_back_images/'),
        ),
        migrations.AddField(
            model_name='item',
            name='front_image',
            field=models.ImageField(blank=True, null=True, upload_to='item_front_images/'),
        ),
    ]
