# Generated by Django 2.1.5 on 2019-08-17 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_brand_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='company.Company'),
        ),
    ]
