# Generated by Django 2.1.6 on 2019-08-21 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20190819_1549'),
        ('product', '0030_auto_20190817_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryaccount',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='company.Company'),
            preserve_default=False,
        ),
    ]
