# Generated by Django 2.1.5 on 2019-08-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_inventoryaccount_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryaccount',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
