# Generated by Django 2.1.5 on 2019-08-23 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_auto_20190822_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalentry',
            old_name='model_id',
            new_name='object_id',
        ),
    ]
