# Generated by Django 2.1.5 on 2019-09-12 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_auto_20190823_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='extra_data',
        ),
    ]
