# Generated by Django 2.1.5 on 2019-09-13 13:29

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_remove_item_extra_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='extra_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
