# Generated by Django 2.1.5 on 2019-09-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0035_item_extra_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='expense',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='expense',
            field=models.BooleanField(default=False),
        ),
    ]
