# Generated by Django 2.1.5 on 2019-09-21 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0025_auto_20190915_1539'),
        ('product', '0036_auto_20190921_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='expense_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_item', to='ledger.Account'),
        ),
    ]
