# Generated by Django 2.1.5 on 2019-09-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0037_item_expense_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='expense',
            new_name='direct_expense',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='expense',
            new_name='direct_expense',
        ),
        migrations.AddField(
            model_name='category',
            name='indirect_expense',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='indirect_expense',
            field=models.BooleanField(default=False),
        ),
    ]
