# Generated by Django 2.1.5 on 2019-09-21 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0025_auto_20190915_1539'),
        ('product', '0038_auto_20190921_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='items_sales_ledger_type',
            new_name='items_sales_account_type',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='sales_ledger',
            new_name='sales_account',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='sales_ledger',
            new_name='sales_account',
        ),
        migrations.AddField(
            model_name='item',
            name='fixed_asset_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_asset_item', to='ledger.Account'),
        ),
    ]
