# Generated by Django 2.1.5 on 2019-09-21 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0039_auto_20190921_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='discount_allowed_ledger',
            new_name='discount_allowed_account',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='discount_received_ledger',
            new_name='discount_received_account',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='items_discount_allowed_ledger_type',
            new_name='items_discount_allowed_account_type',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='items_discount_received_ledger_type',
            new_name='items_discount_received_account_type',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='items_purchase_ledger_type',
            new_name='items_purchase_account_type',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='purchase_ledger',
            new_name='purchase_account',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='discount_allowed_ledger',
            new_name='discount_allowed_account',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='discount_received_ledger',
            new_name='discount_received_account',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='purchase_ledger',
            new_name='purchase_account',
        ),
    ]
