# Generated by Django 2.1.5 on 2019-09-22 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_auto_20190921_1617'),
        ('product', '0040_auto_20190921_2024'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('short_name', 'company')},
        ),
    ]
