# Generated by Django 2.1.5 on 2019-09-22 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_auto_20190921_1617'),
        ('product', '0041_auto_20190922_2251'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('code', 'company'), ('name', 'company')},
        ),
    ]
