# Generated by Django 2.1.5 on 2019-09-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0042_auto_20190922_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryaccount',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
