# Generated by Django 2.1.5 on 2020-02-24 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0042_auto_20200204_2200'),
        ('product', '0043_auto_20190924_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='direct_expense_account_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_expense_account_category', to='ledger.Category'),
        ),
        migrations.AddField(
            model_name='category',
            name='discount_allowed_account_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_allowed_item_categories', to='ledger.Category'),
        ),
        migrations.AddField(
            model_name='category',
            name='discount_received_account_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_received_item_categories', to='ledger.Category'),
        ),
        migrations.AddField(
            model_name='category',
            name='fixed_asset_account_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixed_asset_account_category', to='ledger.Category'),
        ),
        migrations.AddField(
            model_name='category',
            name='indirect_expense_account_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indirect_expense_account_category', to='ledger.Category'),
        ),
        migrations.AddField(
            model_name='category',
            name='parent_account_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_categories', to='ledger.Category'),
        ),
        migrations.AddField(
            model_name='category',
            name='purchase_account_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_item_categories', to='ledger.Category'),
        ),
        migrations.AddField(
            model_name='category',
            name='sales_account_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_item_categories', to='ledger.Category'),
        ),
        migrations.AddField(
            model_name='category',
            name='use_account_category',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='discount_allowed_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_allowed_categories', to='ledger.Account'),
        ),
        migrations.AlterField(
            model_name='category',
            name='discount_received_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_received_categories', to='ledger.Account'),
        ),
        migrations.AlterField(
            model_name='category',
            name='purchase_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_categories', to='ledger.Account'),
        ),
        migrations.AlterField(
            model_name='category',
            name='sales_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_categories', to='ledger.Account'),
        ),
    ]
