# Generated by Django 2.1.5 on 2020-02-27 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0044_auto_20200224_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='use_account_category',
            new_name='use_account_subcategory',
        ),
    ]
