# Generated by Django 2.1.5 on 2020-02-27 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0045_auto_20200227_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='parent_account_category',
            new_name='account_category',
        ),
    ]
