# Generated by Django 2.1.5 on 2020-09-26 08:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0048_auto_20200918_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='extra_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True),
        ),
    ]
