# Generated by Django 4.1.1 on 2022-09-07 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0050_auto_20200926_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='extra_fields',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='extra_data',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
