# Generated by Django 4.2.2 on 2023-10-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0051_alter_category_extra_fields_alter_item_extra_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='source_voucher_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='source_voucher_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
