# Generated by Django 4.2.2 on 2023-10-03 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0052_journalentry_source_voucher_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journalentry',
            old_name='source_voucher_number',
            new_name='source_voucher_no',
        ),
    ]
