# Generated by Django 4.1.1 on 2023-10-15 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0089_remove_company_email_company_emails'),
        ('product', '0053_rename_source_voucher_number_journalentry_source_voucher_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_fifo', models.BooleanField(default=False)),
                ('enable_negative_stock_check', models.BooleanField(default=False)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_setting', to='company.Company')),
            ],
        ),
    ]
