# Generated by Django 4.1.1 on 2023-11-03 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0063_alter_transaction_type'),
        ('product', '0053_rename_source_voucher_number_journalentry_source_voucher_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='dedicated_discount_allowed_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_allowed_item_dedicated', to='ledger.account'),
        ),
        migrations.AddField(
            model_name='item',
            name='dedicated_discount_received_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_received_item_dedicated', to='ledger.account'),
        ),
        migrations.AddField(
            model_name='item',
            name='dedicated_purchase_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_item_dedicated', to='ledger.account'),
        ),
        migrations.AddField(
            model_name='item',
            name='dedicated_sales_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_item_dedicated', to='ledger.account'),
        ),
        migrations.AddField(
            model_name='item',
            name='discount_allowed_account_type',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='discount_received_account_type',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='purchase_account_type',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='sales_account_type',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
