# Generated by Django 4.1.1 on 2023-11-23 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0053_rename_source_voucher_number_journalentry_source_voucher_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='inventoryaccount',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['-id']},
        ),
    ]
