# Generated by Django 4.1.1 on 2023-11-03 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0063_alter_transaction_type'),
        ('product', '0054_item_dedicated_discount_allowed_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='dedicated_discount_allowed_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_allowed_categories_dedicated', to='ledger.account'),
        ),
        migrations.AddField(
            model_name='category',
            name='dedicated_discount_receivd_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_received_categories_dedicated', to='ledger.account'),
        ),
        migrations.AddField(
            model_name='category',
            name='dedicated_purchase_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_categories_dedicated', to='ledger.account'),
        ),
        migrations.AddField(
            model_name='category',
            name='dedicated_sales_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_categories_dedicated', to='ledger.account'),
        ),
    ]
