# Generated by Django 4.1.1 on 2023-11-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0055_category_dedicated_discount_allowed_account_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='dedicated_discount_receivd_account',
            new_name='dedicated_discount_received_account',
        ),
        migrations.AlterField(
            model_name='category',
            name='items_discount_allowed_account_type',
            field=models.CharField(blank=True, choices=[('dedicated', 'Use Dedicated Ledger'), ('global', 'Use Global Ledger'), ('existing', 'Use Existing Ledger')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='items_discount_received_account_type',
            field=models.CharField(blank=True, choices=[('dedicated', 'Use Dedicated Ledger'), ('global', 'Use Global Ledger'), ('existing', 'Use Existing Ledger')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='items_purchase_account_type',
            field=models.CharField(blank=True, choices=[('dedicated', 'Use Dedicated Ledger'), ('global', 'Use Global Ledger'), ('existing', 'Use Existing Ledger')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='items_sales_account_type',
            field=models.CharField(blank=True, choices=[('dedicated', 'Use Dedicated Ledger'), ('global', 'Use Global Ledger'), ('existing', 'Use Existing Ledger')], max_length=100, null=True),
        ),
    ]
