# Generated by Django 4.1.1 on 2023-12-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0055_alter_category_code_alter_item_code"),
    ]

    operations = [
        # migrations.AddField(
        #     model_name="item",
        #     name="voucher_no",
        #     field=models.PositiveBigIntegerField(blank=True, null=True),
        # ),
    ]
