# Generated by Django 4.1.1 on 2023-10-30 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0055_create_inventory_setting_for_existing_companies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
