# Generated by Django 4.1.1 on 2023-12-17 05:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0056_item_voucher_no"),
        (
            "product",
            "0056_rename_dedicated_discount_receivd_account_category_dedicated_discount_received_account_and_more",
        ),
    ]

    operations = []
