# Generated by Django 4.1.1 on 2023-12-26 07:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0055_create_inventory_setting_for_existing_companies"),
        ("product", "0056_item_voucher_no"),
    ]

    operations = []
