# Generated by Django 4.1.1 on 2023-11-23 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0054_alter_brand_options_alter_inventoryaccount_options_and_more'),
        ('product', '0056_rename_dedicated_discount_receivd_account_category_dedicated_discount_received_account_and_more'),
    ]

    operations = [
    ]
