# Generated by Django 4.1.1 on 2023-11-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0056_rename_dedicated_discount_receivd_account_category_dedicated_discount_received_account_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='inventoryaccount',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
