# Generated by Django 4.1.1 on 2023-11-02 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0056_alter_item_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='voucher_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
