# Generated by Django 4.1.1 on 2024-01-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0057_merge_20231226_1303"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryaccount",
            name="opening_balance_rate",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
