# Generated by Django 4.1.1 on 2023-12-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0057_merge_20231217_1130"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="items_discount_allowed_account_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("dedicated", "Use dedicated account"),
                    ("global", "Use global account"),
                    ("existing", "Use existing account"),
                    ("category", "Use category specific account"),
                    ("create", "Choose during item creation"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="items_discount_received_account_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("dedicated", "Use dedicated account"),
                    ("global", "Use global account"),
                    ("existing", "Use existing account"),
                    ("category", "Use category specific account"),
                    ("create", "Choose during item creation"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="items_purchase_account_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("dedicated", "Use dedicated account"),
                    ("global", "Use global account"),
                    ("existing", "Use existing account"),
                    ("category", "Use category specific account"),
                    ("create", "Choose during item creation"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="items_sales_account_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("dedicated", "Use dedicated account"),
                    ("global", "Use global account"),
                    ("existing", "Use existing account"),
                    ("category", "Use category specific account"),
                    ("create", "Choose during item creation"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
