# Generated by Django 4.1.1 on 2023-11-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0057_alter_brand_options_alter_inventoryaccount_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
