# Generated by Django 4.1.1 on 2023-11-02 06:47

from django.db import migrations

def update_item_voucher_no(apps, schema_editor):
    Item = apps.get_model('product', 'Item')
    for item in Item.objects.all():
        item.voucher_no = item.pk
        item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('product', '0057_item_voucher_no'),
    ]

    operations = [
        migrations.RunPython(update_item_voucher_no)
    ]
