# Generated by Django 4.1.1 on 2023-11-02 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0058_auto_20231102_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='voucher_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
