# Generated by Django 4.1.1 on 2024-01-04 05:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0058_inventoryaccount_opening_balance_rate"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryaccount",
            name="opening_quantity",
            field=models.FloatField(default=0),
        ),
    ]
