# Generated by Django 4.1.1 on 2023-11-23 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0057_merge_20231123_1703'),
        ('product', '0058_alter_item_code'),
        ('product', '0059_alter_item_voucher_no'),
    ]

    operations = [
    ]
