# Generated by Django 4.1.1 on 2023-12-19 12:06

from django.db import migrations

def add_defaults(apps, schema_editor):
    Items = apps.get_model('product', 'Item')
    Accounts = apps.get_model('ledger', 'Account')
    """ Your logic here """
    items_list = Items.objects.all()
    for item in items_list:
        # Should be later removed
        if item.sales_account_id and not item.sales_account_type:
            item.sales_account_type = "existing"
        if item.purchase_account_id and not item.purchase_account_type:
            item.purchase_account_type = "existing"
        if item.discount_allowed_account_id and not item.discount_allowed_account_type:
            item.discount_allowed_account_type = "existing"
        if item.discount_received_account_id and not item.discount_received_account_type:
            item.discount_received_account_type = "existing"
    
        # if not item.dedicated_sales_account:
        #     sales_account_name = item.name + ' (Sales)'
        #     dedicated_sales_ac = Accounts.objects.filter(name = sales_account_name).first()
        #     if dedicated_sales_ac:
        #         item.dedicated_sales_account = dedicated_sales_ac
        
        # if not item.dedicated_purchase_account:
        #     purchase_account_name = item.name + ' (Purchase)'
        #     dedicated_purchase_ac = Accounts.objects.filter(name = purchase_account_name).first()
        #     if dedicated_purchase_ac:
        #         item.dedicated_purchase_account = dedicated_purchase_ac
        
        # if not item.dedicated_discount_allowed_account:
        #     discount_allowed_account_name = 'Discount Allowed - ' +  item.name
        #     dedicated_discount_allowed_ac = Accounts.objects.filter(name = discount_allowed_account_name).first()
        #     if dedicated_discount_allowed_ac:
        #         item.dedicated_discount_allowed_account = dedicated_discount_allowed_ac
        
        # if not item.dedicated_discount_received_account:
        #     discount_received_account_name = 'Discount Received - ' + item.name
        #     dedicated_discount_received_ac = Accounts.objects.filter(name = discount_received_account_name).first()
        #     if dedicated_discount_received_ac:
        #         item.dedicated_discount_received_account = dedicated_discount_received_ac

        item.save()

class Migration(migrations.Migration):
    dependencies = [
        ("product", "0059_alter_category_items_discount_allowed_account_type_and_more"),
    ]

    operations = [
        migrations.RunPython(add_defaults)
    ]
