# Generated by Django 4.1.1 on 2023-11-23 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0055_alter_category_code_alter_item_code'),
        ('product', '0060_merge_20231123_1706'),
    ]

    operations = [
    ]
