# Generated by Django 4.1.1 on 2023-11-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0061_merge_20231123_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='voucher_no',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
