# Generated by Django 4.1.1 on 2023-12-25 05:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0060_auto_20231219_1751"),
        ("product", "0062_alter_item_voucher_no"),
    ]

    operations = []
