# Generated by Django 4.1.1 on 2023-12-25 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ledger", "0067_merge_20231123_1759"),
        ("product", "0063_merge_20231225_1108"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="dedicated_discount_allowed_account",
            field=models.ForeignKey(
                blank=True,
                choices=[
                    ("global", "Global"),
                    ("dedicated", "Dedicated"),
                    ("category", "Category"),
                    ("existing", "Existing"),
                ],
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="discount_allowed_item_dedicated",
                to="ledger.account",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="dedicated_discount_received_account",
            field=models.ForeignKey(
                blank=True,
                choices=[
                    ("global", "Global"),
                    ("dedicated", "Dedicated"),
                    ("category", "Category"),
                    ("existing", "Existing"),
                ],
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="discount_received_item_dedicated",
                to="ledger.account",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="dedicated_purchase_account",
            field=models.ForeignKey(
                choices=[
                    ("global", "Global"),
                    ("dedicated", "Dedicated"),
                    ("category", "Category"),
                    ("existing", "Existing"),
                ],
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_item_dedicated",
                to="ledger.account",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="dedicated_sales_account",
            field=models.ForeignKey(
                choices=[
                    ("global", "Global"),
                    ("dedicated", "Dedicated"),
                    ("category", "Category"),
                    ("existing", "Existing"),
                ],
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales_item_dedicated",
                to="ledger.account",
            ),
        ),
    ]
