# Generated by Django 4.1.1 on 2023-12-31 10:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0057_merge_20231226_1303"),
        ("product", "0064_alter_item_dedicated_discount_allowed_account_and_more"),
    ]

    operations = []
