# Generated by Django 4.1.1 on 2024-01-09 15:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0059_inventoryaccount_opening_quantity"),
        ("product", "0065_merge_20231231_1642"),
    ]

    operations = []
