# Generated by Django 4.2.2 on 2024-01-19 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0067_merge_20231123_1759'),
        ('product', '0066_merge_20240109_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='dedicated_discount_allowed_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_allowed_item_dedicated', to='ledger.account'),
        ),
        migrations.AlterField(
            model_name='item',
            name='dedicated_discount_received_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discount_received_item_dedicated', to='ledger.account'),
        ),
        migrations.AlterField(
            model_name='item',
            name='dedicated_purchase_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_item_dedicated', to='ledger.account'),
        ),
        migrations.AlterField(
            model_name='item',
            name='dedicated_sales_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_item_dedicated', to='ledger.account'),
        ),
        migrations.AlterField(
            model_name='item',
            name='discount_allowed_account_type',
            field=models.CharField(blank=True, choices=[('global', 'Global'), ('dedicated', 'Dedicated'), ('category', 'Category'), ('existing', 'Existing')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='discount_received_account_type',
            field=models.CharField(blank=True, choices=[('global', 'Global'), ('dedicated', 'Dedicated'), ('category', 'Category'), ('existing', 'Existing')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='purchase_account_type',
            field=models.CharField(blank=True, choices=[('global', 'Global'), ('dedicated', 'Dedicated'), ('category', 'Category'), ('existing', 'Existing')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='sales_account_type',
            field=models.CharField(blank=True, choices=[('global', 'Global'), ('dedicated', 'Dedicated'), ('category', 'Category'), ('existing', 'Existing')], max_length=16, null=True),
        ),
    ]
