# Generated by Django 4.2.2 on 2024-01-19 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0067_merge_20231123_1759'),
        ('product', '0067_alter_item_dedicated_discount_allowed_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='dedicated_purchase_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_item_dedicated', to='ledger.account'),
        ),
        migrations.AlterField(
            model_name='item',
            name='dedicated_sales_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_item_dedicated', to='ledger.account'),
        ),
        migrations.AlterField(
            model_name='item',
            name='purchase_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_item', to='ledger.account'),
        ),
    ]
