# Generated by Django 4.2.2 on 2024-01-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0068_alter_item_dedicated_purchase_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
