# Generated by Django 4.1.1 on 2024-07-30 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0069_alter_item_extra_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='hs_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
