# Generated by Django 4.1.1 on 2024-02-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0069_alter_item_extra_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
