# Generated by Django 4.1.1 on 2024-02-05 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0070_transaction_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='consumption_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='remaining_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
