# Generated by Django 4.1.1 on 2024-08-15 07:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0070_category_hs_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='hs_code',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000)]),
        ),
    ]
