# Generated by Django 4.2.9 on 2024-02-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0071_transaction_consumption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='fifo_inconsistency_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
