# Generated by Django 4.2.9 on 2024-02-08 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('product', '0072_transaction_fifo_inconsistency_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='FifoInconsistencyLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occured_at', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.PositiveIntegerField()),
                ('quantity', models.FloatField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
