# Generated by Django 4.2.10 on 2024-02-08 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0073_fifoinconsistencylog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fifoinconsistencylog',
            name='quantity',
        ),
        migrations.AddField(
            model_name='fifoinconsistencylog',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fifo_inconsistency_logs', to='product.item'),
            preserve_default=False,
        ),
    ]
