# Generated by Django 4.2.10 on 2024-02-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0074_remove_fifoinconsistencylog_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransatcionRemovalLog',
            fields=[
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('row_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('Ledger', 'Ledger'), ('Inventory', 'Inventory')], max_length=50)),
                ('row_dump', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='FifoInconsistencyLog',
        ),
    ]
