# Generated by Django 4.2.10 on 2024-02-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0075_transatcionremovallog_delete_fifoinconsistencylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='fifo_inconsistency_quantity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
