# Generated by Django 4.2.10 on 2024-02-18 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0076_alter_transaction_fifo_inconsistency_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryaccount',
            name='opening_quantity',
        ),
    ]
