# Generated by Django 4.2.10 on 2024-03-05 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0091_alter_role_modules'),
        ('product', '0077_remove_inventoryaccount_opening_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillOfMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('rate', models.FloatField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_of_material', to='company.Company')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_of_material', to='product.item')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.unit')),
            ],
        ),
        migrations.CreateModel(
            name='BillOfMaterialRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('rate', models.FloatField()),
                ('bill_of_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='product.billofmaterial')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.item')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.unit')),
            ],
        ),
    ]
