# Generated by Django 4.2.10 on 2024-03-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0077_remove_inventoryaccount_opening_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='remaining_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
