# Generated by Django 4.2.10 on 2024-03-05 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0078_billofmaterial_billofmaterialrow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billofmaterial',
            old_name='item',
            new_name='finished_product',
        ),
    ]
