# Generated by Django 4.2.10 on 2024-03-06 09:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0079_rename_item_billofmaterial_finished_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofmaterial',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='billofmaterial',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
