# Generated by Django 4.2.10 on 2024-03-06 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0080_billofmaterial_created_at_billofmaterial_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billofmaterialrow',
            name='rate',
        ),
    ]
