# Generated by Django 4.2.10 on 2024-08-30 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0071_alter_category_hs_code'),
        ('product', '0078_alter_transaction_remaining_quantity'),
        ('product', '0081_remove_billofmaterialrow_rate'),
    ]

    operations = [
    ]
