# Generated by Django 4.2.16 on 2024-09-30 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0083_inventoryadjustmentvoucher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='consumption_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
