# Generated by Django 4.2.16 on 2024-10-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0084_alter_transaction_consumption_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='consumption_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
