# Generated by Django 4.2.16 on 2024-12-03 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('product', '0085_alter_transaction_consumption_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billofmaterial',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_of_material', to='company.company'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='company.company'),
        ),
        migrations.AlterField(
            model_name='category',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
        migrations.AlterField(
            model_name='inventoryaccount',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='company.company'),
        ),
        migrations.AlterField(
            model_name='inventoryadjustmentvoucher',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_adjustment_voucher', to='company.company'),
        ),
        migrations.AlterField(
            model_name='inventoryconversionvoucher',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_conversion_voucher', to='company.company'),
        ),
        migrations.AlterField(
            model_name='inventorysetting',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_setting', to='company.company'),
        ),
        migrations.AlterField(
            model_name='item',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='company.company'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
    ]
