# Generated by Django 4.2.16 on 2024-12-03 04:55

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0096_auto_20241203_1027'),
    ]

    state_operations = [
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start', models.DateField()),
                ('end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('contact_no', models.CharField(max_length=25)),
                ('emails', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, default=list, size=None)),
                ('website', models.URLField(blank=True, null=True)),
                ('organization_type', models.CharField(choices=[('private_limited', 'Private Limited'), ('public_limited', 'Public Limited'), ('sole_proprietorship', 'Sole Proprietorship'), ('partnership', 'Partnership'), ('corporation', 'Corporation'), ('non_profit', 'Non-profit')], default='private_limited', max_length=255)),
                ('tax_registration_number', models.IntegerField()),
                ('enable_sales_invoice_update', models.BooleanField(default=False)),
                ('enable_cheque_deposit_update', models.BooleanField(default=False)),
                ('enable_credit_note_update', models.BooleanField(default=False)),
                ('enable_debit_note_update', models.BooleanField(default=False)),
                ('enable_sales_agents', models.BooleanField(default=False)),
                ('synchronize_cbms_nepal_test', models.BooleanField(default=False)),
                ('synchronize_cbms_nepal_live', models.BooleanField(default=False)),
                ('config_template', models.CharField(default='np', max_length=255)),
                ('invoice_template', models.IntegerField(choices=[(1, 'Template 1'), (2, 'Template 2'), (3, 'Template 3')], default=1)),
                ('current_fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='company.fiscalyear')),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=state_operations,
        ),
    ]
