# Generated by Django 4.2.17 on 2025-02-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
