# Generated by Django 4.2.17 on 2025-02-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_currency'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='companymember',
            name='company_unique_owner',
        ),
        migrations.RenameField(
            model_name='companymember',
            old_name='access_level',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='companymemberinvite',
            old_name='access_level',
            new_name='role',
        ),
        migrations.AddConstraint(
            model_name='companymember',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'owner')), fields=('company', 'role'), name='company_unique_owner'),
        ),
    ]
