# Generated by Django 4.2.17 on 2025-02-18 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_remove_companymember_company_unique_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companymemberinvite',
            name='message',
        ),
        migrations.RemoveField(
            model_name='companymemberinvite',
            name='token',
        ),
    ]
