# Generated by Django 4.2.17 on 2025-02-19 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_remove_companymemberinvite_message_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='currency',
            new_name='currency_code',
        ),
    ]
