# Generated by Django 4.2.19 on 2025-02-24 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_companymemberinvite_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymember',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
