# Generated by Django 4.2.17 on 2025-03-11 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_alter_permission_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='tax_registration_number',
            new_name='tax_identification_number',
        ),
    ]
