# Generated by Django 4.2.17 on 2025-03-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_rename_tax_registration_number_company_tax_identification_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='tax_identification_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
