# Generated by Django 4.2.17 on 2025-04-22 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_alter_company_tax_identification_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymember',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='member_permission', to='company.permission'),
        ),
    ]
