# Generated by Django 4.2.20 on 2025-05-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_alter_company_tax_identification_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='invoice_template',
            field=models.IntegerField(choices=[(1, 'Template 1'), (2, 'Template 2'), (3, 'Template 3'), (4, 'Template 4')], default=1),
        ),
    ]
