# Generated by Django 4.2.20 on 2025-05-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_alter_company_tax_identification_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='corporate_tax_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
