# Generated by Django 4.2.20 on 2025-06-02 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_alter_company_invoice_template'),
        ('company', '0011_company_corporate_tax_rate'),
    ]

    operations = [
    ]
