# Generated by Django 4.2.16 on 2024-12-31 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxScheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('rate', models.FloatField()),
                ('recoverable', models.BooleanField(default=False)),
                ('default', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_schemes', to='company.company')),
                ('payable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payable_taxes', to='ledger.account')),
                ('receivable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receivable_taxes', to='ledger.account')),
            ],
            options={
                'ordering': ['-id'],
                'unique_together': {('short_name', 'company')},
            },
        ),
        migrations.CreateModel(
            name='TaxPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Paid', 'Paid'), ('Cancelled', 'Cancelled')], default='Draft', max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_payments', to='company.company')),
                ('cr_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_payments', to='ledger.account')),
                ('tax_scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='tax.taxscheme')),
            ],
        ),
    ]
